export const copy = {
  title: "Sổ quà của nghệ sĩ",
  backToOverview: "Quay lại tất cả nghệ sĩ",
  period: "Khoảng thời gian",
  today: "Hôm nay",
  thisWeek: "Tuần này",
  thisMonth: "Tháng này",
  lastMonth: "Tháng trước",
  custom: "Tùy chọn",
  from: "Từ ngày",
  to: "Đến ngày",
  apply: "Xem",
  periodRange: "{from} đến {to} ({zone})",
  broker: "Quản lý nghệ sĩ",
  allBrokers: "Tất cả quản lý",
  unassigned: "Chưa phân công (studio trực tiếp quản lý)",
  suspended: "(đã tạm ngưng)",
  search: "Tìm nghệ sĩ",
  exportTable: "Xuất bảng tính",
  exportScopeAll: "Tất cả nghệ sĩ",
  exportScopeUnassigned: "Nghệ sĩ chưa phân công",
  exportScopeBroker: "Tất cả nghệ sĩ của {name}",
  exportScopeMine: "Tất cả nghệ sĩ của tôi",
  archived: "Nghệ sĩ đã xóa",
  exportScopeArtist: "{name}",
  exportFor: "Phạm vi xuất: {scope}",
  exporting: "Đang tạo bảng tính…",
  exported: "Đã tải bảng tính: {file}",
  completed: "Hoàn tất",
  pending: "Đang chờ",
  refunded: "Đã hoàn tiền",
  refundPending: "Đang hoàn tiền: {amount}",
  net: "Thực nhận",
  ordersCount: "{count} đơn",
  test: "Thử nghiệm",
  testNote: "Thanh toán thử nghiệm, không phải tiền thật",
  artist: "Nghệ sĩ",
  assignedBroker: "Quản lý nghệ sĩ",
  noBroker: "Chưa phân công",
  empty: "Không có món quà nào được thanh toán trong khoảng thời gian này.",
  noMatch: "Không có nghệ sĩ nào khớp với tìm kiếm.",
  loading: "Đang tải sổ quà…",
  loadError: "Hiện chưa thể hiển thị sổ quà.",
  retry: "Thử lại",
  rulesTitle: "Cách tính số liệu",
  ruleTime:
    "Quà được tính khi thanh toán thành công trong khoảng thời gian, theo ngày của {zone}. Số tiền và trạng thái là mới nhất nên các khoản hoàn tiền sau đó cũng được trừ.",
  ruleCompleted:
    "Hoàn tất: đã thanh toán, đã giao và chưa hoàn tiền toàn bộ; đã trừ tiền hoàn. Quà ảo được giao ngay khi thanh toán.",
  rulePending:
    "Đang chờ: đã thanh toán, vẫn đang chờ chuẩn bị, đang chuẩn bị hoặc tạm giữ và chưa hoàn tiền toàn bộ.",
  ruleRefunded:
    "Đã hoàn tiền: số tiền đã hoàn thành công cho món quà. Đơn thua tranh chấp thanh toán được tính là hoàn lại toàn bộ đơn. Khoản đang hoàn tiền được ghi riêng và không bị trừ.",
  ruleExcluded:
    "Không tính đơn chưa thanh toán hoặc đã hủy. Số đơn tính theo đơn hàng; nhiều món quà cho cùng một nghệ sĩ trong một đơn vẫn tính là 1.",
  ruleCurrency:
    "Mỗi loại tiền tệ được cộng riêng và không bao giờ cộng gộp; thanh toán thử nghiệm được liệt kê riêng.",
  pendingList: "Đang chờ",
  completedList: "Hoàn tất",
  closedList: "Đã hoàn tiền hoặc đã đóng",
  orderNumber: "Đơn hàng",
  paidAt: "Thanh toán lúc",
  gift: "Quà",
  quantity: "SL",
  amount: "Số tiền",
  status: "Trạng thái",
  waiting: "Đã chờ",
  waitingDays: "{count} ngày",
  netAmount: "Thực nhận",
  deliveredAt: "Giao lúc",
  message: "Lời nhắn",
  statusPending: "Chờ chuẩn bị",
  statusPreparing: "Đang chuẩn bị",
  statusOnHold: "Tạm giữ",
  statusDelivered: "Đã giao",
  statusCanceled: "Đã hủy",
  statusRefunded: "Đã hoàn tiền toàn bộ",
  chargebackLost: "Thua tranh chấp thanh toán",
  truncated:
    "Chỉ hiển thị 10.000 món quà gần nhất. Hãy chọn khoảng thời gian ngắn hơn để xem phần còn lại.",
  noLines:
    "Nghệ sĩ này không có món quà nào được thanh toán trong khoảng thời gian này.",
  exportArtist: "Xuất nghệ sĩ này",
  viewMessage: "Xem lời nhắn",
  hideMessage: "Ẩn",
  messageLoading: "Đang mở…",
  messageAudit: "Mỗi lần mở đều được ghi lại. Tự đóng sau 5 phút.",
  signature: "Ký tên",
  anonymous: "Ẩn danh",
  noMessageText: "(không có lời nhắn)",
  messageUnavailable:
    "Không thể hiển thị lời nhắn này; studio có thể đã chặn hoặc xóa.",
  languageRequired:
    "Tài khoản của bạn không được phép mở lời nhắn bằng ngôn ngữ này.",
  kindVirtual: "Quà ảo",
  kindPhysical: "Quà hiện vật",
  kindWish: "Mong ước của nghệ sĩ",
  kindMerchandise: "Hàng lưu niệm",
  kindOther: "Khác",
  sheetSummary: "Tổng hợp",
  sheetDetails: "Chi tiết",
  workbookTitle: "Sổ quà của nghệ sĩ",
  exportScope: "Phạm vi",
  exportPeriod: "Khoảng thời gian",
  timeZone: "Múi giờ",
  exportedBy: "Người xuất",
  exportedAt: "Thời điểm xuất",
  notice: "Ghi chú",
  noticeText:
    "Chỉ dùng để đối soát nội bộ. Mỗi loại tiền tệ được cộng riêng, thanh toán thử nghiệm được liệt kê riêng. Không có email, chữ ký hay lời nhắn của người hâm mộ.",
  environment: "Loại thanh toán",
  live: "Thật",
  currency: "Tiền tệ",
  completedOrders: "Số đơn hoàn tất",
  completedAmount: "Số tiền hoàn tất",
  pendingOrders: "Số đơn đang chờ",
  pendingAmount: "Số tiền đang chờ",
  refundPendingAmount: "Đang hoàn tiền",
  unitPrice: "Đơn giá",
  kind: "Loại",
  totalRow: "Tổng",
  truncatedSheet:
    "Chi tiết chỉ gồm 10.000 món quà gần nhất; hãy xuất khoảng thời gian ngắn hơn để có phần còn lại.",
  fileName: "artist-ledger",
};
