export const copy = {
  title: "Registro por artista",
  backToOverview: "Volver a todos los artistas",
  period: "Periodo",
  today: "Hoy",
  thisWeek: "Esta semana",
  thisMonth: "Este mes",
  lastMonth: "Mes anterior",
  custom: "Personalizado",
  from: "Desde",
  to: "Hasta",
  apply: "Mostrar",
  periodRange: "Del {from} al {to} ({zone})",
  broker: "Representante",
  allBrokers: "Todos los representantes",
  unassigned: "Sin asignar (gestionados por el estudio)",
  suspended: "(suspendido)",
  search: "Buscar artistas",
  exportTable: "Exportar hoja de cálculo",
  exportScopeAll: "Todos los artistas",
  exportScopeUnassigned: "Artistas sin asignar",
  exportScopeBroker: "Todos los artistas de {name}",
  exportScopeMine: "Todos mis artistas",
  archived: "Artista eliminado",
  exportScopeArtist: "{name}",
  exportFor: "Se exporta: {scope}",
  exporting: "Preparando la hoja de cálculo…",
  exported: "Hoja de cálculo descargada: {file}",
  completed: "Completados",
  pending: "Pendientes",
  refunded: "Reembolsado",
  refundPending: "Reembolso en curso: {amount}",
  net: "Ingreso neto",
  ordersCount: "{count} pedidos",
  test: "Prueba",
  testNote: "Pagos de prueba, no dinero real",
  artist: "Artista",
  assignedBroker: "Representante",
  noBroker: "Sin asignar",
  empty: "No se pagó ningún regalo en este periodo.",
  noMatch: "Ningún artista coincide con la búsqueda.",
  loading: "Cargando el registro…",
  loadError: "El registro no está disponible en este momento.",
  retry: "Reintentar",
  rulesTitle: "Cómo se calculan las cifras",
  ruleTime:
    "Cuentan los regalos cuyo pago se completó dentro del periodo, según los días de {zone}. Los importes y estados son los más recientes, así que los reembolsos posteriores también se descuentan.",
  ruleCompleted:
    "Completados: pagados, entregados y sin reembolso total; los reembolsos ya están descontados. Los regalos virtuales se entregan al pagarse.",
  rulePending:
    "Pendientes: pagados y aún por preparar, en preparación o en pausa, sin reembolso total.",
  ruleRefunded:
    "Reembolsado: dinero devuelto por el regalo. Si se pierde una disputa de pago, se devuelve el pedido completo. Los reembolsos en curso se muestran aparte y no se descuentan.",
  ruleExcluded:
    "No cuentan los pedidos sin pagar ni los cancelados. Los pedidos se cuentan una vez por artista aunque incluyan varios regalos.",
  ruleCurrency:
    "Cada moneda tiene sus propios totales y nunca se suma a otra; los pagos de prueba se muestran aparte.",
  pendingList: "Pendientes",
  completedList: "Completados",
  closedList: "Reembolsados o cerrados",
  orderNumber: "Pedido",
  paidAt: "Pagado",
  gift: "Regalo",
  quantity: "Cant.",
  amount: "Importe",
  status: "Estado",
  waiting: "En espera",
  waitingDays: "{count} días",
  netAmount: "Neto",
  deliveredAt: "Entregado",
  message: "Mensaje",
  statusPending: "Por preparar",
  statusPreparing: "En preparación",
  statusOnHold: "En pausa",
  statusDelivered: "Entregado",
  statusCanceled: "Cancelado",
  statusRefunded: "Reembolsado por completo",
  chargebackLost: "Disputa de pago perdida",
  truncated:
    "Solo se muestran los 10.000 regalos más recientes. Elige un periodo más corto para ver el resto.",
  noLines: "Este artista no recibió regalos pagados en este periodo.",
  exportArtist: "Exportar este artista",
  viewMessage: "Ver mensaje",
  hideMessage: "Ocultar",
  messageLoading: "Abriendo…",
  messageAudit:
    "Cada apertura queda registrada. Se cierra sola a los 5 minutos.",
  signature: "Firma",
  anonymous: "Anónimo",
  noMessageText: "(sin mensaje)",
  messageUnavailable:
    "Este mensaje no se puede mostrar; es posible que el estudio lo haya retenido o eliminado.",
  languageRequired:
    "Tu cuenta no tiene permiso para abrir mensajes en este idioma.",
  kindVirtual: "Regalo virtual",
  kindPhysical: "Regalo físico",
  kindWish: "Deseo del artista",
  kindMerchandise: "Merchandising",
  kindOther: "Otro",
  sheetSummary: "Resumen",
  sheetDetails: "Detalle",
  workbookTitle: "Registro de regalos por artista",
  exportScope: "Alcance",
  exportPeriod: "Periodo",
  timeZone: "Zona horaria",
  exportedBy: "Exportado por",
  exportedAt: "Exportado el",
  notice: "Nota",
  noticeText:
    "Solo para conciliación interna. Cada moneda se totaliza por separado y los pagos de prueba se muestran aparte. No incluye correos, firmas ni mensajes de los fans.",
  environment: "Tipo de pago",
  live: "Real",
  currency: "Moneda",
  completedOrders: "Pedidos completados",
  completedAmount: "Importe completado",
  pendingOrders: "Pedidos pendientes",
  pendingAmount: "Importe pendiente",
  refundPendingAmount: "Reembolso en curso",
  unitPrice: "Precio unitario",
  kind: "Tipo",
  totalRow: "Total",
  truncatedSheet:
    "El detalle solo incluye los 10.000 regalos más recientes; exporta un periodo más corto para el resto.",
  fileName: "artist-ledger",
};
