export const copy = {
  title: "Artist ledger",
  backToOverview: "Back to all artists",
  period: "Period",
  today: "Today",
  thisWeek: "This week",
  thisMonth: "This month",
  lastMonth: "Last month",
  custom: "Custom",
  from: "From",
  to: "To",
  apply: "Show",
  periodRange: "{from} to {to} ({zone})",
  broker: "Broker",
  allBrokers: "All brokers",
  unassigned: "Unassigned (managed by the studio)",
  suspended: "(suspended)",
  search: "Search artists",
  exportTable: "Export spreadsheet",
  exportScopeAll: "All artists",
  exportScopeUnassigned: "Unassigned artists",
  exportScopeBroker: "All artists of {name}",
  exportScopeMine: "All my artists",
  archived: "Deleted artist",
  exportScopeArtist: "{name}",
  exportFor: "Exports: {scope}",
  exporting: "Preparing the spreadsheet…",
  exported: "Spreadsheet downloaded: {file}",
  completed: "Completed",
  pending: "Pending",
  refunded: "Refunded",
  refundPending: "Refund in progress: {amount}",
  net: "Net received",
  ordersCount: "{count} orders",
  test: "Test",
  testNote: "Test payments, not real money",
  artist: "Artist",
  assignedBroker: "Broker",
  noBroker: "Unassigned",
  empty: "No gifts were paid for in this period.",
  noMatch: "No artist matches this search.",
  loading: "Loading the ledger…",
  loadError: "The ledger is unavailable right now.",
  retry: "Try again",
  rulesTitle: "How the figures are counted",
  ruleTime:
    "Gifts count when their payment succeeded inside the period, by {zone} calendar days. Amounts and states are the latest, so later refunds are deducted.",
  ruleCompleted:
    "Completed: paid, delivered and not fully refunded; refunds are deducted. Virtual gifts are delivered as soon as they are paid.",
  rulePending:
    "Pending: paid and still pending, being prepared or on hold, and not fully refunded.",
  ruleRefunded:
    "Refunded: money returned on the gift. A lost chargeback returns the whole order. Refunds still in progress are shown apart and not deducted.",
  ruleExcluded:
    "Unpaid and cancelled orders are not counted. Orders are counted once per artist even with several gifts.",
  ruleCurrency:
    "Each currency has its own totals and is never added to another; test payments are listed apart.",
  pendingList: "Pending",
  completedList: "Completed",
  closedList: "Refunded or closed",
  orderNumber: "Order",
  paidAt: "Paid",
  gift: "Gift",
  quantity: "Qty",
  amount: "Amount",
  status: "Status",
  waiting: "Waiting",
  waitingDays: "{count} days",
  netAmount: "Net",
  deliveredAt: "Delivered",
  message: "Message",
  statusPending: "To prepare",
  statusPreparing: "Preparing",
  statusOnHold: "On hold",
  statusDelivered: "Delivered",
  statusCanceled: "Cancelled",
  statusRefunded: "Fully refunded",
  chargebackLost: "Chargeback lost",
  truncated:
    "Only the latest 10,000 gifts are shown. Choose a shorter period to see the rest.",
  noLines: "This artist received no paid gifts in this period.",
  exportArtist: "Export this artist",
  viewMessage: "Show message",
  hideMessage: "Hide",
  messageLoading: "Opening…",
  messageAudit:
    "Every opening is recorded. It closes by itself after 5 minutes.",
  signature: "Signed",
  anonymous: "Anonymous",
  noMessageText: "(no message)",
  messageUnavailable:
    "This message cannot be shown; the studio may have withheld or removed it.",
  languageRequired:
    "Your account is not allowed to open messages in this language.",
  kindVirtual: "Virtual gift",
  kindPhysical: "Physical gift",
  kindWish: "Artist wish",
  kindMerchandise: "Merchandise",
  kindOther: "Other",
  sheetSummary: "Summary",
  sheetDetails: "Details",
  workbookTitle: "Artist gift ledger",
  exportScope: "Scope",
  exportPeriod: "Period",
  timeZone: "Time zone",
  exportedBy: "Exported by",
  exportedAt: "Exported at",
  notice: "Note",
  noticeText:
    "For internal reconciliation. Currencies are totalled separately and test payments are listed apart. No fan emails, signatures or messages.",
  environment: "Payment",
  live: "Live",
  currency: "Currency",
  completedOrders: "Completed orders",
  completedAmount: "Completed amount",
  pendingOrders: "Pending orders",
  pendingAmount: "Pending amount",
  refundPendingAmount: "Refund in progress",
  unitPrice: "Unit price",
  kind: "Type",
  totalRow: "Total",
  truncatedSheet:
    "Only the latest 10,000 gifts are included; export a shorter period for the rest.",
  fileName: "artist-ledger",
};
