export const copy = {
  title: "アーティスト別台帳",
  backToOverview: "すべてのアーティストに戻る",
  period: "期間",
  today: "今日",
  thisWeek: "今週",
  thisMonth: "今月",
  lastMonth: "先月",
  custom: "期間を指定",
  from: "開始日",
  to: "終了日",
  apply: "表示",
  periodRange: "{from}〜{to}（{zone}）",
  broker: "担当マネージャー",
  allBrokers: "すべてのマネージャー",
  unassigned: "未割り当て（スタジオ直轄）",
  suspended: "（停止中）",
  search: "アーティストを検索",
  exportTable: "表を書き出す",
  exportScopeAll: "すべてのアーティスト",
  exportScopeUnassigned: "未割り当てのアーティスト",
  exportScopeBroker: "{name} の担当アーティスト全員",
  exportScopeMine: "担当アーティスト全員",
  archived: "削除済みのアーティスト",
  exportScopeArtist: "{name}",
  exportFor: "書き出し範囲：{scope}",
  exporting: "表を作成しています…",
  exported: "表をダウンロードしました：{file}",
  completed: "完了",
  pending: "対応待ち",
  refunded: "返金済み",
  refundPending: "返金処理中：{amount}",
  net: "純受取額",
  ordersCount: "{count} 件",
  test: "テスト",
  testNote: "テスト決済のため実際の入金ではありません",
  artist: "アーティスト",
  assignedBroker: "担当マネージャー",
  noBroker: "未割り当て",
  empty: "この期間に支払い済みのギフトはありません。",
  noMatch: "検索に一致するアーティストはいません。",
  loading: "台帳を読み込んでいます…",
  loadError: "現在、台帳を表示できません。",
  retry: "再試行",
  rulesTitle: "集計方法",
  ruleTime:
    "支払いが成功した日時が期間内にあるギフトを、{zone}の日付で集計します。金額と状態は最新のため、後から行われた返金も差し引かれます。",
  ruleCompleted:
    "完了：支払い済み・お届け済みで全額返金されていないもの。返金額は差し引き済みです。バーチャルギフトは支払いと同時にお届け済みになります。",
  rulePending:
    "対応待ち：支払い済みで、準備待ち・準備中・保留中のまま全額返金されていないもの。",
  ruleRefunded:
    "返金済み：ギフトに対して返金が完了した金額。チャージバックで敗訴した注文は注文全体を返金扱いにします。処理中の返金は別に表示し、差し引きません。",
  ruleExcluded:
    "未払い・キャンセル済みの注文は含みません。件数は注文単位で、同じ注文で同じアーティストに複数のギフトを贈っても 1 件です。",
  ruleCurrency:
    "通貨ごとに別々に合計し、合算しません。テスト決済は別に表示します。",
  pendingList: "対応待ち",
  completedList: "完了",
  closedList: "返金済み・終了",
  orderNumber: "注文番号",
  paidAt: "支払日時",
  gift: "ギフト",
  quantity: "数量",
  amount: "金額",
  status: "状態",
  waiting: "経過",
  waitingDays: "{count} 日",
  netAmount: "差引額",
  deliveredAt: "お届け日時",
  message: "メッセージ",
  statusPending: "準備待ち",
  statusPreparing: "準備中",
  statusOnHold: "保留中",
  statusDelivered: "お届け済み",
  statusCanceled: "キャンセル済み",
  statusRefunded: "全額返金済み",
  chargebackLost: "チャージバック敗訴",
  truncated:
    "最新の 10,000 件のみ表示しています。残りは期間を短くしてご確認ください。",
  noLines: "このアーティストには、この期間に支払い済みのギフトはありません。",
  exportArtist: "このアーティストを書き出す",
  viewMessage: "メッセージを見る",
  hideMessage: "閉じる",
  messageLoading: "開いています…",
  messageAudit: "閲覧するたびに記録されます。5 分後に自動で閉じます。",
  signature: "署名",
  anonymous: "匿名",
  noMessageText: "（メッセージなし）",
  messageUnavailable:
    "このメッセージは表示できません。スタジオが非公開にしたか削除した可能性があります。",
  languageRequired:
    "このアカウントには、この言語のメッセージを見る権限がありません。",
  kindVirtual: "バーチャルギフト",
  kindPhysical: "実物ギフト",
  kindWish: "アーティストの願い",
  kindMerchandise: "グッズ",
  kindOther: "その他",
  sheetSummary: "集計",
  sheetDetails: "明細",
  workbookTitle: "アーティスト別ギフト台帳",
  exportScope: "書き出し範囲",
  exportPeriod: "期間",
  timeZone: "タイムゾーン",
  exportedBy: "書き出した人",
  exportedAt: "書き出し日時",
  notice: "注記",
  noticeText:
    "社内の照合専用です。通貨ごとに別々に合計し、テスト決済は別に記載しています。ファンのメールアドレス・署名・メッセージは含みません。",
  environment: "決済の種類",
  live: "本番",
  currency: "通貨",
  completedOrders: "完了件数",
  completedAmount: "完了金額",
  pendingOrders: "対応待ち件数",
  pendingAmount: "対応待ち金額",
  refundPendingAmount: "返金処理中",
  unitPrice: "単価",
  kind: "種類",
  totalRow: "合計",
  truncatedSheet:
    "明細には最新の 10,000 件のみ含まれます。残りは期間を短くして書き出してください。",
  fileName: "artist-ledger",
};
