export const copy = {
  title: "艺人账目",
  backToOverview: "返回全部艺人",
  period: "时段",
  today: "今天",
  thisWeek: "本周",
  thisMonth: "本月",
  lastMonth: "上月",
  custom: "自定义",
  from: "开始日期",
  to: "结束日期",
  apply: "查看",
  periodRange: "{from} 至 {to}（{zone}）",
  broker: "经纪人",
  allBrokers: "全部经纪人",
  unassigned: "未分配（超管直管）",
  suspended: "（已停用）",
  search: "搜索艺人",
  exportTable: "导出表格",
  exportScopeAll: "全部艺人",
  exportScopeUnassigned: "未分配的艺人",
  exportScopeBroker: "{name} 名下全部艺人",
  exportScopeMine: "我名下的全部艺人",
  archived: "已删除的艺人",
  exportScopeArtist: "{name}",
  exportFor: "导出范围：{scope}",
  exporting: "正在生成表格…",
  exported: "表格已下载：{file}",
  completed: "已完成",
  pending: "待处理",
  refunded: "已退款",
  refundPending: "退款处理中：{amount}",
  net: "净收合计",
  ordersCount: "{count} 笔",
  test: "测试",
  testNote: "测试付款，不是真实收款",
  artist: "艺人",
  assignedBroker: "归属经纪人",
  noBroker: "未分配",
  empty: "该时段没有已付款的礼物。",
  noMatch: "没有符合搜索的艺人。",
  loading: "正在加载账目…",
  loadError: "暂时无法加载账目。",
  retry: "重试",
  rulesTitle: "统计说明",
  ruleTime:
    "按付款成功时间落在所选时段内的礼物统计，日期按{zone}划分；金额和状态取当前最新，之后发生的退款也会扣掉。",
  ruleCompleted:
    "已完成：已付款、这件礼物已送达、没有被全额退款；金额已扣除退款。虚拟礼物付款即送达。",
  rulePending: "待处理：已付款、还在待准备、准备中或暂缓，且没有被全额退款。",
  ruleRefunded:
    "已退款：已成功退到这件礼物上的金额；拒付败诉的订单整单算退回。退款处理中的金额单独注明，不算已退。",
  ruleExcluded:
    "未付款、已取消的订单不计入。笔数按订单算，同一订单给同一位艺人买了几件礼物也算 1 笔。",
  ruleCurrency: "不同币种分开合计，永不相加；测试付款单独列出。",
  pendingList: "待处理",
  completedList: "已完成",
  closedList: "已退款或已关闭",
  orderNumber: "订单号",
  paidAt: "付款时间",
  gift: "礼物",
  quantity: "数量",
  amount: "金额",
  status: "状态",
  waiting: "已等待",
  waitingDays: "{count} 天",
  netAmount: "净额",
  deliveredAt: "送达时间",
  message: "留言",
  statusPending: "待准备",
  statusPreparing: "准备中",
  statusOnHold: "暂缓",
  statusDelivered: "已送达",
  statusCanceled: "已取消",
  statusRefunded: "已全额退款",
  chargebackLost: "拒付败诉",
  truncated: "只显示最近的 10000 件礼物；请缩短时段查看其余部分。",
  noLines: "这位艺人在该时段没有已付款的礼物。",
  exportArtist: "导出该艺人",
  viewMessage: "查看留言",
  hideMessage: "收起",
  messageLoading: "正在读取…",
  messageAudit: "每次查看都会留下记录，5 分钟后自动收起。",
  signature: "署名",
  anonymous: "匿名",
  noMessageText: "（没有留言）",
  messageUnavailable: "这条留言不可查看，可能已被工作室拦截或删除。",
  languageRequired: "你的账号没有查看这种语言留言的授权。",
  kindVirtual: "虚拟打赏",
  kindPhysical: "实物投喂",
  kindWish: "艺人心愿",
  kindMerchandise: "周边",
  kindOther: "其他",
  sheetSummary: "汇总",
  sheetDetails: "明细",
  workbookTitle: "艺人收礼账目",
  exportScope: "导出范围",
  exportPeriod: "时段",
  timeZone: "时区",
  exportedBy: "导出人",
  exportedAt: "导出时间",
  notice: "说明",
  noticeText:
    "仅供内部对账。不同币种分开合计，测试付款单独列出。不含粉丝邮箱、署名和留言。",
  environment: "付款类型",
  live: "正式",
  currency: "币种",
  completedOrders: "已完成笔数",
  completedAmount: "已完成金额",
  pendingOrders: "待处理笔数",
  pendingAmount: "待处理金额",
  refundPendingAmount: "退款处理中",
  unitPrice: "单价",
  kind: "类型",
  totalRow: "合计",
  truncatedSheet: "明细只包含最近的 10000 件礼物；其余部分请缩短时段再导出。",
  fileName: "艺人账目",
};
