export const copy = {
  title: "Registro por artista",
  backToOverview: "Voltar para todos os artistas",
  period: "Período",
  today: "Hoje",
  thisWeek: "Esta semana",
  thisMonth: "Este mês",
  lastMonth: "Mês passado",
  custom: "Personalizado",
  from: "De",
  to: "Até",
  apply: "Mostrar",
  periodRange: "De {from} a {to} ({zone})",
  broker: "Agente",
  allBrokers: "Todos os agentes",
  unassigned: "Sem agente (gerenciados pelo estúdio)",
  suspended: "(suspenso)",
  search: "Buscar artistas",
  exportTable: "Exportar planilha",
  exportScopeAll: "Todos os artistas",
  exportScopeUnassigned: "Artistas sem agente",
  exportScopeBroker: "Todos os artistas de {name}",
  exportScopeMine: "Todos os meus artistas",
  archived: "Artista excluído",
  exportScopeArtist: "{name}",
  exportFor: "Será exportado: {scope}",
  exporting: "Preparando a planilha…",
  exported: "Planilha baixada: {file}",
  completed: "Concluídos",
  pending: "Pendentes",
  refunded: "Reembolsado",
  refundPending: "Reembolso em andamento: {amount}",
  net: "Receita líquida",
  ordersCount: "{count} pedidos",
  test: "Teste",
  testNote: "Pagamentos de teste, não dinheiro real",
  artist: "Artista",
  assignedBroker: "Agente",
  noBroker: "Sem agente",
  empty: "Nenhum presente foi pago neste período.",
  noMatch: "Nenhum artista corresponde à busca.",
  loading: "Carregando o registro…",
  loadError: "O registro não está disponível no momento.",
  retry: "Tentar novamente",
  rulesTitle: "Como os números são calculados",
  ruleTime:
    "Contam os presentes cujo pagamento foi concluído dentro do período, pelos dias de {zone}. Valores e situações são os mais recentes, então reembolsos posteriores também são descontados.",
  ruleCompleted:
    "Concluídos: pagos, entregues e sem reembolso total; os reembolsos já foram descontados. Presentes virtuais são entregues no pagamento.",
  rulePending:
    "Pendentes: pagos e ainda aguardando preparo, em preparo ou em espera, sem reembolso total.",
  ruleRefunded:
    "Reembolsado: valor devolvido pelo presente. Se uma contestação de pagamento for perdida, o pedido inteiro é devolvido. Reembolsos em andamento aparecem à parte e não são descontados.",
  ruleExcluded:
    "Pedidos não pagos e cancelados não contam. Cada pedido conta uma vez por artista, mesmo com vários presentes.",
  ruleCurrency:
    "Cada moeda tem seus próprios totais e nunca é somada a outra; pagamentos de teste aparecem à parte.",
  pendingList: "Pendentes",
  completedList: "Concluídos",
  closedList: "Reembolsados ou encerrados",
  orderNumber: "Pedido",
  paidAt: "Pago em",
  gift: "Presente",
  quantity: "Qtd.",
  amount: "Valor",
  status: "Situação",
  waiting: "Aguardando",
  waitingDays: "{count} dias",
  netAmount: "Líquido",
  deliveredAt: "Entregue em",
  message: "Mensagem",
  statusPending: "A preparar",
  statusPreparing: "Em preparo",
  statusOnHold: "Em espera",
  statusDelivered: "Entregue",
  statusCanceled: "Cancelado",
  statusRefunded: "Reembolsado integralmente",
  chargebackLost: "Contestação de pagamento perdida",
  truncated:
    "Somente os 10.000 presentes mais recentes são exibidos. Escolha um período menor para ver o restante.",
  noLines: "Este artista não recebeu presentes pagos neste período.",
  exportArtist: "Exportar este artista",
  viewMessage: "Ver mensagem",
  hideMessage: "Ocultar",
  messageLoading: "Abrindo…",
  messageAudit: "Cada abertura é registrada. Fecha sozinha após 5 minutos.",
  signature: "Assinatura",
  anonymous: "Anônimo",
  noMessageText: "(sem mensagem)",
  messageUnavailable:
    "Esta mensagem não pode ser exibida; o estúdio pode tê-la retido ou removido.",
  languageRequired:
    "Sua conta não tem permissão para abrir mensagens neste idioma.",
  kindVirtual: "Presente virtual",
  kindPhysical: "Presente físico",
  kindWish: "Desejo do artista",
  kindMerchandise: "Produtos oficiais",
  kindOther: "Outro",
  sheetSummary: "Resumo",
  sheetDetails: "Detalhes",
  workbookTitle: "Registro de presentes por artista",
  exportScope: "Abrangência",
  exportPeriod: "Período",
  timeZone: "Fuso horário",
  exportedBy: "Exportado por",
  exportedAt: "Exportado em",
  notice: "Observação",
  noticeText:
    "Somente para conciliação interna. Cada moeda é totalizada separadamente e pagamentos de teste aparecem à parte. Não inclui e-mails, assinaturas ou mensagens dos fãs.",
  environment: "Tipo de pagamento",
  live: "Real",
  currency: "Moeda",
  completedOrders: "Pedidos concluídos",
  completedAmount: "Valor concluído",
  pendingOrders: "Pedidos pendentes",
  pendingAmount: "Valor pendente",
  refundPendingAmount: "Reembolso em andamento",
  unitPrice: "Preço unitário",
  kind: "Tipo",
  totalRow: "Total",
  truncatedSheet:
    "Os detalhes incluem somente os 10.000 presentes mais recentes; exporte um período menor para o restante.",
  fileName: "artist-ledger",
};
