export const copy = {
  orders: "Đơn hàng",
  searchOrders: "Tìm theo mã đơn hàng",
  allOrders: "Tất cả đơn hàng",
  reviewFilter: "Duyệt lời nhắn",
  needsReview: "Cần duyệt",
  noOrders: "Không có đơn hàng phù hợp.",
  loading: "Đang tải đơn hàng…",
  noAccess: "Tài khoản này chưa được cấp khu vực làm việc.",
  loadError: "Không thể tải khu vực làm việc.",
  retryAction: "Thử lại thao tác",
  orderDate: "Ngày đặt hàng",
  recipient: "Dành tặng",
  orderLanguage: "Ngôn ngữ đặt hàng",
  reviewCount: "Chờ duyệt",
  pending: "Chờ chuẩn bị",
  preparing: "Đang chuẩn bị",
  delivered: "Đã trao tặng",
  onHold: "Tạm giữ",
  canceled: "Đã hủy",
  unpaid: "Chưa thanh toán",
  paid: "Đã thanh toán",
  partiallyRefunded: "Hoàn tiền một phần",
  refunded: "Đã hoàn tiền",
  paymentPending: "Chờ thanh toán",
  dispute: "Tranh chấp thanh toán",
  status: "Trạng thái",
  prepare: "Bắt đầu chuẩn bị",
  deliver: "Đánh dấu đã trao tặng",
  hold: "Tạm giữ",
  resume: "Tiếp tục chuẩn bị",
  reviewMessage: "Mở lời nhắn riêng tư",
  closePrivate: "Đóng nội dung riêng tư",
  privateHint: "Nội dung riêng tư chỉ hiển thị khi bảng này đang mở.",
  reviewLanguage: "Ngôn ngữ duyệt",
  confirmLanguage:
    "Tôi hiểu ngôn ngữ này và đã xem toàn bộ lời nhắn cùng tên hiển thị.",
  approve: "Duyệt",
  reject: "Từ chối",
  approved: "Đã duyệt",
  rejected: "Đã từ chối",
  redacted: "Đã ẩn",
  noMessage: "Không có lời nhắn",
  languageUnverified: "Ngôn ngữ cần được xác nhận thủ công",
  privateExpired: "Quyền xem đã hết hạn. Hãy đóng rồi mở lại.",
  notes: "Ghi chú nội bộ",
  openNotes: "Mở ghi chú",
  addNote: "Thêm ghi chú",
  noteHint:
    "Chỉ ghi thông tin liên quan đến đơn hàng. Không sao chép thông tin thanh toán hoặc địa chỉ riêng.",
  saveNote: "Lưu ghi chú",
  notification: "Thông báo",
  resend: "Gửi lại cập nhật mới nhất",
  queued: "Thông báo đã vào hàng đợi. Kết quả gửi sẽ được xác nhận riêng.",
  notificationSent: "Đã gửi",
  notificationFailed: "Gửi thất bại",
  notificationWaiting: "Chờ gửi",
  notificationUnknown: "Chưa xác nhận gửi",
  unavailable: "Không khả dụng",
  managerActions: "Xử lý ngoại lệ",
  reason: "Lý do",
  reasonDelay: "Chuẩn bị bị chậm",
  reasonSafety: "Cần kiểm tra an toàn",
  reasonResolved: "Đã giải quyết vấn đề",
  confirmChange: "Tôi xác nhận thay đổi trạng thái này.",
  saved: "Đã lưu",
  conflict: "Đơn hàng đã thay đổi. Hãy tải lại trước khi tiếp tục.",
  forbidden: "Bạn không có quyền thực hiện thao tác này.",
  failure: "Chưa thể xác nhận kết quả. Thử lại để khôi phục cùng yêu cầu.",
  paymentRequired: "Thanh toán chưa được xác nhận. Chưa thể chuẩn bị quà.",
  moderationRequired: "Hãy duyệt lời nhắn riêng tư trước khi chuẩn bị quà.",
  languageRequired: "Cần người có quyền duyệt ngôn ngữ phù hợp.",
  throttled: "Vui lòng chờ trước khi thử lại.",
  waiting: "Đang xử lý…",
  studioDelivery: "Studio chuẩn bị và trao mọi món quà đến nghệ sĩ.",
  legacy: "Thông tin lịch sử",
};
