export const copy = {
  orders: "注文",
  searchOrders: "注文番号で検索",
  allOrders: "すべての注文",
  reviewFilter: "メッセージ審査",
  needsReview: "要審査",
  noOrders: "該当する注文はありません。",
  loading: "注文を読み込み中…",
  noAccess: "このアカウントには作業権限がありません。",
  loadError: "作業画面を読み込めませんでした。",
  retryAction: "操作を再試行",
  orderDate: "注文日時",
  recipient: "贈り先",
  orderLanguage: "注文時の言語",
  reviewCount: "審査待ち",
  pending: "準備待ち",
  preparing: "準備中",
  delivered: "お届け済み",
  onHold: "保留中",
  canceled: "キャンセル済み",
  unpaid: "未払い",
  paid: "支払い済み",
  partiallyRefunded: "一部返金済み",
  refunded: "返金済み",
  paymentPending: "支払い待ち",
  dispute: "支払いの異議",
  status: "状態",
  prepare: "準備を開始",
  deliver: "お届け済みにする",
  hold: "保留にする",
  resume: "準備を再開",
  reviewMessage: "非公開メッセージを開く",
  closePrivate: "非公開表示を閉じる",
  privateHint: "非公開内容はこのパネルを開いている間だけ表示されます。",
  reviewLanguage: "審査言語",
  confirmLanguage: "この言語を理解し、メッセージ全文と名前を確認しました。",
  approve: "承認",
  reject: "拒否",
  approved: "承認済み",
  rejected: "拒否済み",
  redacted: "削除済み",
  noMessage: "メッセージなし",
  languageUnverified: "言語の確認が必要です",
  privateExpired: "閲覧期限が切れました。閉じてから開き直してください。",
  notes: "内部メモ",
  openNotes: "メモを開く",
  addNote: "メモを追加",
  noteHint:
    "注文に関する内容だけを記録し、決済情報や個人住所は入力しないでください。",
  saveNote: "メモを保存",
  notification: "通知",
  resend: "最新状況を再送",
  queued: "通知を送信待ちに追加しました。配信結果は別途確認されます。",
  notificationSent: "送信済み",
  notificationFailed: "送信失敗",
  notificationWaiting: "送信待ち",
  notificationUnknown: "配信結果未確認",
  unavailable: "利用不可",
  managerActions: "例外対応",
  reason: "理由",
  reasonDelay: "準備の遅延",
  reasonSafety: "安全確認が必要",
  reasonResolved: "問題解決済み",
  confirmChange: "この状態変更を確認しました。",
  saved: "保存しました",
  conflict: "注文が更新されました。再読み込みしてから操作してください。",
  forbidden: "この操作の権限がありません。",
  failure: "結果を確認できませんでした。再試行すると同じ操作を復旧できます。",
  paymentRequired: "支払いが未確認のため準備できません。",
  moderationRequired: "準備前に非公開メッセージを審査してください。",
  languageRequired: "権限を持つ担当者による言語審査が必要です。",
  throttled: "少し待ってから再試行してください。",
  waiting: "処理中…",
  studioDelivery: "すべてのギフトはスタジオが準備し、アーティストへ届けます。",
  digitalDelivery: "デジタル応援記録：決済確認後に自動でお届けします。",
  deliverTitle: "お届けを確定",
  proofIntro:
    "お届けしたギフトの写真を最大3枚追加できます。購入者だけが、非公開の注文ページで確認できます。",
  proofPrivacy:
    "アップロードする前に、他の人の顔、番地、住所、配送ラベルを切り取ってください。",
  proofChoose: "写真を選択",
  proofRemove: "写真を削除",
  proofConfirmPrivacy:
    "これらの写真から他の人の顔と住所の情報を切り取りました。",
  proofOptional: "写真は任意です。後から追加することもできます。",
  confirmDelivery: "お届けを確定",
  addProofs: "お届け写真を追加",
  saveProofs: "写真を保存",
  cancel: "キャンセル",
  proofUploading: "写真をアップロードしています…",
  proofSaving: "写真を保存しています…",
  proofDelivering: "お届け済みにしています…",
  proofInvalid:
    "この写真は使用できません。各辺320ピクセル以上のJPEG、PNG、WebPの写真を選んでください。",
  proofLimit: "このギフトにはすでに写真が3枚あります。",
  proofFormat: "JPEG、PNG、WebPの写真のみ選択できます。",
  proofs: "お届け写真",
  viewProofs: "写真を表示",
  hideProofs: "写真を閉じる",
  proofAlt: "お届け写真",
  withdrawProof: "写真を取り下げる",
  reasonProofPrivacy: "個人情報が写っている",
  reasonProofWrongOrder: "別の注文の写真",
  reasonProofQuality: "写真が不鮮明",
  confirmWithdraw: "この写真を購入者に表示しないことを確認します。",
  legacy: "過去の記録",
};
