export const copy = {
  orders: "Orders",
  searchOrders: "Search order number",
  allOrders: "All orders",
  reviewFilter: "Message review",
  needsReview: "Needs review",
  noOrders: "No matching orders.",
  loading: "Loading orders…",
  noAccess: "No workspace is assigned to this account.",
  loadError: "We could not load this workspace.",
  retryAction: "Retry this action",
  orderDate: "Order date",
  recipient: "For",
  orderLanguage: "Order language",
  reviewCount: "Awaiting review",
  pending: "Pending",
  preparing: "Preparing",
  delivered: "Delivered",
  onHold: "On hold",
  canceled: "Canceled",
  unpaid: "Unpaid",
  paid: "Paid",
  partiallyRefunded: "Partially refunded",
  refunded: "Refunded",
  paymentPending: "Payment pending",
  dispute: "Payment dispute",
  status: "Status",
  prepare: "Start preparation",
  deliver: "Mark delivered",
  hold: "Put on hold",
  resume: "Resume preparation",
  reviewMessage: "Open private message",
  closePrivate: "Close private view",
  privateHint: "Private content is shown only while this panel is open.",
  reviewLanguage: "Review language",
  confirmLanguage:
    "I understand this language and have reviewed the full message and name.",
  approve: "Approve",
  reject: "Reject",
  approved: "Approved",
  rejected: "Rejected",
  redacted: "Redacted",
  noMessage: "No message",
  languageUnverified: "Language requires human confirmation",
  privateExpired: "Private access expired. Close and reopen to continue.",
  notes: "Internal notes",
  openNotes: "Open notes",
  addNote: "Add a note",
  noteHint:
    "Keep notes relevant to this order. Do not copy payment credentials or private addresses.",
  saveNote: "Save note",
  notification: "Notification",
  resend: "Resend latest update",
  queued: "Notification queued. Delivery will be confirmed separately.",
  notificationSent: "Sent",
  notificationFailed: "Delivery failed",
  notificationWaiting: "Waiting to send",
  notificationUnknown: "Delivery unconfirmed",
  unavailable: "Unavailable",
  managerActions: "Exception handling",
  reason: "Reason",
  reasonDelay: "Preparation delayed",
  reasonSafety: "Safety review required",
  reasonResolved: "Issue resolved",
  confirmChange: "I confirm this status change.",
  saved: "Saved",
  conflict: "This order changed. Reload it before trying again.",
  forbidden: "You do not have permission for this action.",
  failure:
    "We could not confirm the action. Retry to recover the same request.",
  paymentRequired: "Payment is not confirmed. Preparation is unavailable.",
  moderationRequired: "Review the private message before preparing this gift.",
  languageRequired: "An authorized language review is required.",
  throttled: "Please wait before trying again.",
  waiting: "Working…",
  studioDelivery: "The studio prepares and delivers every gift to the artist.",
  digitalDelivery:
    "Digital support record: delivered automatically once payment is confirmed.",
  deliverTitle: "Confirm delivery",
  proofIntro:
    "Add up to three photos of the delivered gift. Only the buyer sees them, on their private order page.",
  proofPrivacy:
    "Before uploading, crop out other people's faces, house numbers, addresses and shipping labels.",
  proofChoose: "Choose photos",
  proofRemove: "Remove photo",
  proofConfirmPrivacy:
    "I removed other people's faces and any address details from these photos.",
  proofOptional: "Photos are optional. You can add them later.",
  confirmDelivery: "Confirm delivery",
  addProofs: "Add delivery photos",
  saveProofs: "Save photos",
  cancel: "Cancel",
  proofUploading: "Uploading photos…",
  proofSaving: "Saving photos…",
  proofDelivering: "Marking delivered…",
  proofInvalid:
    "This photo could not be used. Choose a JPEG, PNG or WebP photo at least 320 pixels on each side.",
  proofLimit: "This gift already has three photos.",
  proofFormat: "Choose JPEG, PNG or WebP photos only.",
  proofs: "Delivery photos",
  viewProofs: "View photos",
  hideProofs: "Hide photos",
  proofAlt: "Delivery photo",
  withdrawProof: "Withdraw photo",
  reasonProofPrivacy: "Shows private details",
  reasonProofWrongOrder: "Belongs to another order",
  reasonProofQuality: "Photo is unclear",
  confirmWithdraw: "I confirm the buyer should no longer see this photo.",
  legacy: "Historical record",
};
