export const copy = {
  orders: "Pedidos",
  searchOrders: "Buscar número de pedido",
  allOrders: "Todos los pedidos",
  reviewFilter: "Revisión de mensajes",
  needsReview: "Pendiente de revisión",
  noOrders: "No hay pedidos coincidentes.",
  loading: "Cargando pedidos…",
  noAccess: "Esta cuenta no tiene un área de trabajo asignada.",
  loadError: "No se pudo cargar el área de trabajo.",
  retryAction: "Reintentar esta acción",
  orderDate: "Fecha del pedido",
  recipient: "Para",
  orderLanguage: "Idioma del pedido",
  reviewCount: "Pendiente de revisión",
  pending: "Pendiente",
  preparing: "En preparación",
  delivered: "Entregado",
  onHold: "En espera",
  canceled: "Cancelado",
  unpaid: "Sin pagar",
  paid: "Pagado",
  partiallyRefunded: "Reembolso parcial",
  refunded: "Reembolsado",
  paymentPending: "Pago pendiente",
  dispute: "Disputa de pago",
  status: "Estado",
  prepare: "Iniciar preparación",
  deliver: "Marcar como entregado",
  hold: "Poner en espera",
  resume: "Reanudar preparación",
  reviewMessage: "Abrir mensaje privado",
  closePrivate: "Cerrar contenido privado",
  privateHint:
    "El contenido privado solo se muestra mientras este panel está abierto.",
  reviewLanguage: "Idioma de revisión",
  confirmLanguage:
    "Entiendo este idioma y he revisado el mensaje completo y el nombre.",
  approve: "Aprobar",
  reject: "Rechazar",
  approved: "Aprobado",
  rejected: "Rechazado",
  redacted: "Suprimido",
  noMessage: "Sin mensaje",
  languageUnverified: "El idioma requiere confirmación humana",
  privateExpired:
    "El acceso privado ha caducado. Cierra y vuelve a abrir el panel.",
  notes: "Notas internas",
  openNotes: "Abrir notas",
  addNote: "Añadir una nota",
  noteHint:
    "Incluye solo información del pedido. No copies credenciales de pago ni direcciones privadas.",
  saveNote: "Guardar nota",
  notification: "Notificación",
  resend: "Reenviar la última actualización",
  queued:
    "La notificación está en cola. La entrega se confirmará por separado.",
  notificationSent: "Enviada",
  notificationFailed: "Error de entrega",
  notificationWaiting: "Pendiente de envío",
  notificationUnknown: "Entrega sin confirmar",
  unavailable: "No disponible",
  managerActions: "Gestión de excepciones",
  reason: "Motivo",
  reasonDelay: "Preparación retrasada",
  reasonSafety: "Requiere revisión de seguridad",
  reasonResolved: "Problema resuelto",
  confirmChange: "Confirmo este cambio de estado.",
  saved: "Guardado",
  conflict: "El pedido ha cambiado. Recárgalo antes de continuar.",
  forbidden: "No tienes permiso para esta acción.",
  failure:
    "No se pudo confirmar la acción. Reintenta para recuperar la misma solicitud.",
  paymentRequired:
    "El pago no está confirmado. No se puede iniciar la preparación.",
  moderationRequired:
    "Revisa el mensaje privado antes de preparar este regalo.",
  languageRequired: "Se requiere una revisión lingüística autorizada.",
  throttled: "Espera un momento antes de volver a intentarlo.",
  waiting: "Procesando…",
  studioDelivery: "El estudio prepara y entrega todos los regalos al artista.",
  digitalDelivery:
    "Registro de apoyo digital: se entrega automáticamente al confirmarse el pago.",
  legacy: "Registro histórico",
};
