export const copy = {
  orders: "Pedidos",
  searchOrders: "Pesquisar número do pedido",
  allOrders: "Todos os pedidos",
  reviewFilter: "Revisão de mensagens",
  needsReview: "A aguardar revisão",
  noOrders: "Nenhum pedido encontrado.",
  loading: "A carregar pedidos…",
  noAccess: "Esta conta não tem uma área de trabalho atribuída.",
  loadError: "Não foi possível carregar esta área de trabalho.",
  retryAction: "Repetir esta ação",
  orderDate: "Data do pedido",
  recipient: "Para",
  orderLanguage: "Idioma do pedido",
  reviewCount: "A aguardar revisão",
  pending: "Pendente",
  preparing: "Em preparação",
  delivered: "Entregue",
  onHold: "Em espera",
  canceled: "Cancelado",
  unpaid: "Por pagar",
  paid: "Pago",
  partiallyRefunded: "Reembolso parcial",
  refunded: "Reembolsado",
  paymentPending: "Pagamento pendente",
  dispute: "Disputa de pagamento",
  status: "Estado",
  prepare: "Iniciar preparação",
  deliver: "Marcar como entregue",
  hold: "Colocar em espera",
  resume: "Retomar preparação",
  reviewMessage: "Abrir mensagem privada",
  closePrivate: "Fechar conteúdo privado",
  privateHint:
    "O conteúdo privado é apresentado apenas enquanto este painel estiver aberto.",
  reviewLanguage: "Idioma de revisão",
  confirmLanguage:
    "Compreendo este idioma e revi a mensagem completa e o nome.",
  approve: "Aprovar",
  reject: "Rejeitar",
  approved: "Aprovado",
  rejected: "Rejeitado",
  redacted: "Suprimido",
  noMessage: "Sem mensagem",
  languageUnverified: "O idioma requer confirmação humana",
  privateExpired: "O acesso privado expirou. Feche e volte a abrir o painel.",
  notes: "Notas internas",
  openNotes: "Abrir notas",
  addNote: "Adicionar nota",
  noteHint:
    "Registe apenas informações do pedido. Não copie credenciais de pagamento nem endereços privados.",
  saveNote: "Guardar nota",
  notification: "Notificação",
  resend: "Reenviar a atualização mais recente",
  queued:
    "A notificação foi colocada na fila. A entrega será confirmada separadamente.",
  notificationSent: "Enviada",
  notificationFailed: "Falha na entrega",
  notificationWaiting: "A aguardar envio",
  notificationUnknown: "Entrega não confirmada",
  unavailable: "Indisponível",
  managerActions: "Gestão de exceções",
  reason: "Motivo",
  reasonDelay: "Preparação atrasada",
  reasonSafety: "Revisão de segurança necessária",
  reasonResolved: "Problema resolvido",
  confirmChange: "Confirmo esta alteração de estado.",
  saved: "Guardado",
  conflict: "O pedido foi alterado. Recarregue antes de continuar.",
  forbidden: "Não tem permissão para esta ação.",
  failure:
    "Não foi possível confirmar a ação. Repita para recuperar o mesmo pedido.",
  paymentRequired:
    "O pagamento não foi confirmado. A preparação está indisponível.",
  moderationRequired:
    "Reveja a mensagem privada antes de preparar este presente.",
  languageRequired: "É necessária uma revisão linguística autorizada.",
  throttled: "Aguarde um momento antes de tentar novamente.",
  waiting: "A processar…",
  studioDelivery: "O estúdio prepara e entrega todos os presentes ao artista.",
  digitalDelivery:
    "Registro de apoio digital: entregue automaticamente após a confirmação do pagamento.",
  deliverTitle: "Confirmar a entrega",
  proofIntro:
    "Adicione até três fotografias do presente entregue. Só o comprador as vê, na página privada do pedido.",
  proofPrivacy:
    "Antes de carregar, recorte os rostos de outras pessoas, números de porta, moradas e etiquetas de envio.",
  proofChoose: "Escolher fotografias",
  proofRemove: "Remover fotografia",
  proofConfirmPrivacy:
    "Recortei destas fotografias os rostos de outras pessoas e quaisquer dados de morada.",
  proofOptional: "As fotografias são opcionais. Pode adicioná-las mais tarde.",
  confirmDelivery: "Confirmar a entrega",
  addProofs: "Adicionar fotografias da entrega",
  saveProofs: "Guardar fotografias",
  cancel: "Cancelar",
  proofUploading: "A carregar fotografias…",
  proofSaving: "A guardar fotografias…",
  proofDelivering: "A marcar como entregue…",
  proofInvalid:
    "Não foi possível usar esta fotografia. Escolha uma fotografia JPEG, PNG ou WebP com pelo menos 320 píxeis de cada lado.",
  proofLimit: "Este presente já tem três fotografias.",
  proofFormat: "Escolha apenas fotografias JPEG, PNG ou WebP.",
  proofs: "Fotografias da entrega",
  viewProofs: "Ver fotografias",
  hideProofs: "Ocultar fotografias",
  proofAlt: "Fotografia da entrega",
  withdrawProof: "Retirar fotografia",
  reasonProofPrivacy: "Mostra dados privados",
  reasonProofWrongOrder: "Pertence a outro pedido",
  reasonProofQuality: "A fotografia não está nítida",
  confirmWithdraw:
    "Confirmo que o comprador não deve voltar a ver esta fotografia.",
  legacy: "Registo histórico",
};
