import type { ManagementCopy } from "./copy";
export const copy = {
  login: "ログイン",
  loginHint: "ログインしてアーティスト、ギフト、ポスターを管理します。",
  loginFailed: "ログインできませんでした。もう一度お試しください。",
  sessionExpired: "セッションが終了しました。再度ログインしてください。",
  sessionUnavailable:
    "セッションを確認できませんでした。もう一度お試しください。",
  logout: "ログアウト",
  logoutFailed: "ログアウトを確認できませんでした。もう一度お試しください。",

  center: "管理センター",
  artists: "アーティスト",
  gifts: "ギフト",
  posters: "トップ画像",
  addArtist: "アーティストを追加",
  addGift: "ギフトを追加",
  replacePoster: "画像を変更",
  back: "一覧に戻る",
  edit: "編集",
  save: "保存して公開",
  addAndPublish: "追加して公開",
  upload: "画像を選ぶ",
  changeImage: "画像を変更",
  imageHint: "JPEG・PNG・WebP。画像の縦横比を保ちます。",
  name: "名前",
  description: "説明",
  price: "価格",
  kind: "ギフトの種類",
  category: "カテゴリー",
  options: "その他の設定",
  sourceLanguage: "内容の言語",
  rightsNotice:
    "送信すると、画像と内容を公開する権利があることを確認したものとします。",
  uploading: "画像をアップロード中…",
  processing: "処理して公開しています…",
  published: "公開済み",
  retry: "再試行",
  loadFailed: "一覧を読み込めませんでした。再試行してください。",
  emptyArtists: "最初のアーティストを追加しましょう。",
  emptyGifts: "最初のギフトを追加しましょう。",
  emptyPosters: "過去の画像はまだありません。",
  current: "使用中",
  history: "過去の画像",
  restore: "この画像に戻す",
  previous: "前へ",
  next: "次へ",
  search: "検索",
  searchPlaceholder: "名前で検索",
  noResults: "一致する内容がありません。",
  checkingSession: "管理画面を開いています…",
  sessionMissing: "セッションを利用できません。再接続してください。",
  reconnect: "再接続",
  inventory: "販売方式",
  inventoryPolicyLocked:
    "在庫の記録があるため、販売方式は変更できません。数量やその他のギフト情報は引き続き編集できます。",
  madeToOrder: "注文ごとに準備",
  tracked: "数量限定の在庫",
  preorder: "予約販売",
  quantity: "在庫数",
  location: "在庫の保管場所",
  market: "販売地域",
  currency: "通貨",
  noMarket: "価格を設定する前に販売地域と通貨を設定してください。",
  noLocation: "利用可能な在庫保管場所がありません。",
  viewStorefront: "サイトで確認",
  imageFormat: "JPEG・PNG・WebP画像を選んでください。",
  imageEmpty: "ファイルが空です。別の画像を選んでください。",
  imageRequired: "画像を選んでください。",
  required: "この項目を入力してください。",
  invalidPrice: "この通貨で有効な価格を入力してください。",
  invalidQuantity: "0以上の整数を入力してください。",
  sourceTooSmall: "画像が小さすぎます。大きい元画像を選んでください。",
  forbidden: "この変更を公開する権限がありません。",
  conflict: "内容が更新されました。一覧を再読み込みして編集してください。",
  network: "接続が中断されました。再試行して同じ更新を続けられます。",
  failedProcessing: "更新を完了できませんでした。再試行してください。",
  reloadList: "一覧を再読み込み",
  untitled: "名称未設定",
  virtual: "バーチャルギフト",
  physical: "実物のギフト",
  wish: "ウィッシュギフト",
  merchandise: "グッズ",
  other: "その他",
  flowers: "花",
  food: "食品",
  beauty: "美容",
  accessory: "アクセサリー",
  posterUnavailable:
    "画像を変更する前にアーティストとトップページを設定してください。",
  original: "原文",
  pendingUpdates: "更新中",
  draft: "下書き",
  paused: "一時停止",
  archived: "アーカイブ済み",
  imageUnavailable: "画像を表示できません",
  readOnly: "閲覧のみ",
} satisfies ManagementCopy;
