import type { ManagementCopy } from "./copy";
export const copy = {
  interfaceLanguage: "Idioma de la interfaz",
  discardEdits: "¿Descartar los cambios sin guardar y salir de esta página?",
  adjustFocus: "Ajustar el enfoque del recorte",
  focusHint:
    "Elige el sujeto en la foto original. Usa las flechas para moverlo poco o Mayús + flecha para moverlo más.",
  focusHorizontal: "Enfoque horizontal",
  focusVertical: "Enfoque vertical",
  resetFocus: "Restablecer enfoque",
  previewPortrait: "Retrato",
  previewDesktop: "Banner de escritorio",
  previewMobile: "Banner móvil",
  previewGift: "Foto del regalo",
  originalLoading: "Cargando la foto original…",
  originalUnavailable:
    "No se pudo cargar la foto original. Inténtalo de nuevo; tus cambios se conservan.",
  reuploadRequired: "Vuelve a subir la foto original para ajustar esta imagen.",
  imageUnchanged: "Elige una nueva foto o ajusta el enfoque antes de publicar.",

  login: "Iniciar sesión",
  loginHint: "Inicia sesión para gestionar artistas, regalos y carteles.",
  loginFailed: "No se pudo iniciar sesión. Inténtalo de nuevo.",
  sessionExpired: "Tu sesión ha finalizado. Vuelve a iniciar sesión.",
  sessionUnavailable: "No se pudo comprobar tu sesión. Inténtalo de nuevo.",
  logout: "Cerrar sesión",
  logoutFailed: "No se pudo confirmar el cierre de sesión. Inténtalo de nuevo.",

  center: "Centro de gestión",
  artists: "Artistas",
  gifts: "Regalos",
  posters: "Imagen de inicio",
  addArtist: "Añadir artista",
  addGift: "Añadir regalo",
  replacePoster: "Cambiar imagen",
  back: "Volver a la lista",
  edit: "Editar",
  save: "Guardar y publicar",
  addAndPublish: "Añadir y publicar",
  upload: "Elegir imagen",
  changeImage: "Cambiar imagen",
  imageHint:
    "JPEG, PNG o WebP. La foto se recorta para llenar cada espacio de visualización.",
  imageBestSize: "Recomendado: al menos {width} × {height} px.",
  imageTipArtist: "Coloca el rostro en la parte superior.",
  imageTipGift: "Coloca el regalo en el centro.",
  imageTipPoster:
    "Coloca el motivo en el centro; en móviles solo se ve la parte central.",
  imageTooSmall:
    "Esta imagen mide {width} × {height} px, menos de lo recomendado, y puede verse borrosa en pantallas grandes.",
  name: "Nombre",
  description: "Descripción",
  price: "Precio",
  kind: "Tipo de regalo",
  category: "Categoría",
  options: "Más ajustes",
  sourceLanguage: "Idioma del contenido",
  rightsNotice:
    "Al enviar, confirmas que puedes publicar estas imágenes y este contenido.",
  uploading: "Subiendo imagen…",
  processing: "Procesando y publicando…",
  published: "Publicado",
  retry: "Reintentar",
  loadFailed: "No se pudo cargar la lista. Inténtalo de nuevo.",
  emptyArtists: "Añade tu primer artista.",
  emptyGifts: "Añade tu primer regalo.",
  emptyPosters: "Todavía no hay imágenes anteriores.",
  current: "Actual",
  history: "Imágenes anteriores",
  restore: "Restaurar esta imagen",
  previous: "Anterior",
  next: "Siguiente",
  search: "Buscar",
  searchPlaceholder: "Buscar por nombre",
  noResults: "No hay resultados coincidentes.",
  checkingSession: "Abriendo tu espacio…",
  sessionMissing: "La sesión no está disponible. Vuelve a conectar.",
  reconnect: "Volver a conectar",
  inventory: "Disponibilidad",
  inventoryPolicyLocked:
    "Ya existen registros de inventario, por lo que debe mantenerse esta forma de venta. Puedes editar la cantidad y los demás datos del regalo.",
  madeToOrder: "Preparar por pedido",
  tracked: "Existencias limitadas",
  preorder: "Preventa",
  quantity: "Cantidad disponible",
  location: "Ubicación de existencias",
  market: "Mercado",
  currency: "Moneda",
  noMarket: "Configura el mercado y la moneda antes de fijar el precio.",
  noLocation: "No hay ubicaciones de existencias disponibles.",
  viewStorefront: "Ver en el sitio",
  imageFormat: "Elige una imagen JPEG, PNG o WebP.",
  imageEmpty: "El archivo está vacío. Elige otra imagen.",
  imageRequired: "Elige una imagen primero.",
  required: "Completa este campo.",
  invalidPrice: "Introduce un precio válido para esta moneda.",
  invalidQuantity: "Introduce un número entero igual o mayor que cero.",
  sourceTooSmall:
    "La imagen es demasiado pequeña. Elige un original más grande.",
  forbidden: "No tienes permiso para publicar este cambio.",
  conflict: "El contenido ha cambiado. Recarga la lista antes de editar.",
  network:
    "Se interrumpió la conexión. Reintenta para continuar esta actualización.",
  failedProcessing:
    "No se pudo completar la actualización. Inténtalo de nuevo.",
  reloadList: "Recargar lista",
  untitled: "Sin nombre",
  virtual: "Regalo virtual",
  physical: "Regalo físico",
  wish: "Regalo de deseo",
  merchandise: "Artículos de colección",
  other: "Otros",
  flowers: "Flores",
  food: "Alimentos",
  beauty: "Belleza",
  accessory: "Accesorios",
  posterUnavailable:
    "Publica un artista y la página de inicio antes de cambiar la imagen.",
  original: "Contenido original",
  pendingUpdates: "Actualizaciones en curso",
  draft: "Borrador",
  paused: "En pausa",
  archived: "Archivado",
  imageUnavailable: "Imagen no disponible",
  readOnly: "Solo lectura",
  deleteTitle: "Eliminar definitivamente",
  deleteWarning:
    "Se quitará del sitio web y de esta lista. No se puede deshacer. Los pedidos existentes conservan su registro.",
  deleteTypeName: "Escribe el nombre exacto para confirmar",
  deleteConfirm: "Eliminar definitivamente",
  deleted: "Eliminado. Ya no aparece en el sitio web.",
} satisfies ManagementCopy;
