import type { ManagementCopy } from "./copy";
export const copy = {
  login: "เข้าสู่ระบบ",
  loginHint: "เข้าสู่ระบบเพื่อจัดการศิลปิน ของขวัญ และโปสเตอร์",
  loginFailed: "เข้าสู่ระบบไม่สำเร็จ โปรดลองอีกครั้ง",
  sessionExpired: "เซสชันสิ้นสุดแล้ว โปรดเข้าสู่ระบบอีกครั้ง",
  sessionUnavailable: "ยังตรวจสอบเซสชันไม่ได้ โปรดลองอีกครั้ง",
  logout: "ออกจากระบบ",
  logoutFailed: "ยังยืนยันการออกจากระบบไม่ได้ โปรดลองอีกครั้ง",

  center: "ศูนย์จัดการ",
  artists: "ศิลปิน",
  gifts: "ของขวัญ",
  posters: "ภาพหน้าหลัก",
  addArtist: "เพิ่มศิลปิน",
  addGift: "เพิ่มของขวัญ",
  replacePoster: "เปลี่ยนภาพ",
  back: "กลับไปยังรายการ",
  edit: "แก้ไข",
  save: "บันทึกและเผยแพร่",
  addAndPublish: "เพิ่มและเผยแพร่",
  upload: "เลือกรูปภาพ",
  changeImage: "เปลี่ยนรูปภาพ",
  imageHint: "JPEG, PNG หรือ WebP โดยคงสัดส่วนเดิม",
  name: "ชื่อ",
  description: "คำอธิบาย",
  price: "ราคา",
  kind: "ประเภทของขวัญ",
  category: "หมวดหมู่",
  options: "การตั้งค่าเพิ่มเติม",
  sourceLanguage: "ภาษาของเนื้อหา",
  rightsNotice: "เมื่อส่ง คุณยืนยันว่ามีสิทธิ์เผยแพร่รูปภาพและเนื้อหานี้",
  uploading: "กำลังอัปโหลดรูปภาพ…",
  processing: "กำลังเตรียมและเผยแพร่…",
  published: "เผยแพร่แล้ว",
  retry: "ลองอีกครั้ง",
  loadFailed: "โหลดรายการไม่ได้ โปรดลองอีกครั้ง",
  emptyArtists: "เพิ่มศิลปินคนแรก",
  emptyGifts: "เพิ่มของขวัญชิ้นแรก",
  emptyPosters: "ยังไม่มีภาพก่อนหน้า",
  current: "ใช้อยู่",
  history: "ภาพก่อนหน้า",
  restore: "ใช้ภาพนี้อีกครั้ง",
  previous: "ก่อนหน้า",
  next: "ถัดไป",
  search: "ค้นหา",
  searchPlaceholder: "ค้นหาด้วยชื่อ",
  noResults: "ไม่พบผลลัพธ์ที่ตรงกัน",
  checkingSession: "กำลังเปิดพื้นที่จัดการ…",
  sessionMissing: "เซสชันไม่พร้อมใช้งาน โปรดเชื่อมต่อใหม่",
  reconnect: "เชื่อมต่อใหม่",
  inventory: "รูปแบบการจำหน่าย",
  inventoryPolicyLocked:
    "มีข้อมูลสต็อกแล้ว จึงต้องคงรูปแบบการจำหน่ายเดิมไว้ คุณยังแก้ไขจำนวนและรายละเอียดของขวัญอื่น ๆ ได้",
  madeToOrder: "เตรียมตามคำสั่งซื้อ ขายซ้ำได้",
  tracked: "สินค้ามีจำนวนจำกัด",
  preorder: "สั่งจองล่วงหน้า",
  quantity: "จำนวนสินค้า",
  location: "สถานที่เก็บสินค้า",
  market: "ตลาด",
  currency: "สกุลเงิน",
  noMarket: "โปรดตั้งค่าตลาดและสกุลเงินก่อนกำหนดราคา",
  noLocation: "ไม่มีสถานที่เก็บสินค้าที่ใช้ได้",
  viewStorefront: "ดูบนเว็บไซต์",
  imageFormat: "โปรดเลือกรูป JPEG, PNG หรือ WebP",
  imageEmpty: "ไฟล์นี้ว่างเปล่า โปรดเลือกรูปอื่น",
  imageRequired: "โปรดเลือกรูปภาพก่อน",
  required: "โปรดกรอกช่องนี้",
  invalidPrice: "โปรดกรอกราคาที่ถูกต้องสำหรับสกุลเงินนี้",
  invalidQuantity: "โปรดกรอกจำนวนเต็มตั้งแต่ศูนย์ขึ้นไป",
  sourceTooSmall: "รูปภาพเล็กเกินไป โปรดเลือกต้นฉบับที่ใหญ่ขึ้น",
  forbidden: "บัญชีนี้ไม่มีสิทธิ์เผยแพร่การเปลี่ยนแปลงนี้",
  conflict: "เนื้อหานี้เปลี่ยนไปแล้ว โปรดโหลดรายการใหม่ก่อนแก้ไข",
  network: "การเชื่อมต่อขัดข้อง ลองอีกครั้งเพื่อทำต่อ",
  failedProcessing: "อัปเดตไม่สำเร็จ โปรดลองอีกครั้ง",
  reloadList: "โหลดรายการใหม่",
  untitled: "ไม่มีชื่อ",
  virtual: "ของขวัญเสมือน",
  physical: "ของขวัญจริง",
  wish: "ของขวัญตามความปรารถนา",
  merchandise: "สินค้าที่ระลึก",
  other: "อื่น ๆ",
  flowers: "ดอกไม้",
  food: "อาหาร",
  beauty: "ความงาม",
  accessory: "เครื่องประดับ",
  posterUnavailable: "โปรดเพิ่มศิลปินและตั้งค่าหน้าหลักก่อนเปลี่ยนภาพ",
  original: "เนื้อหาต้นฉบับ",
  pendingUpdates: "กำลังอัปเดต",
  draft: "ฉบับร่าง",
  paused: "หยุดชั่วคราว",
  archived: "เก็บถาวรแล้ว",
  imageUnavailable: "รูปภาพไม่พร้อมใช้งาน",
  readOnly: "ดูได้อย่างเดียว",
} satisfies ManagementCopy;
