import type { ManagementCopy } from "./copy";
export const copy = {
  center: "Centro de gestión",
  artists: "Artistas",
  gifts: "Regalos",
  posters: "Imagen de inicio",
  addArtist: "Añadir artista",
  addGift: "Añadir regalo",
  replacePoster: "Cambiar imagen",
  back: "Volver a la lista",
  edit: "Editar",
  save: "Guardar y publicar",
  addAndPublish: "Añadir y publicar",
  upload: "Elegir imagen",
  changeImage: "Cambiar imagen",
  imageHint: "JPEG, PNG o WebP. Se conservan las proporciones.",
  name: "Nombre",
  description: "Descripción",
  price: "Precio",
  kind: "Tipo de regalo",
  category: "Categoría",
  options: "Más ajustes",
  sourceLanguage: "Idioma del contenido",
  rightsNotice:
    "Al enviar, confirmas que puedes publicar estas imágenes y este contenido.",
  uploading: "Subiendo imagen…",
  processing: "Procesando y publicando…",
  published: "Publicado",
  retry: "Reintentar",
  loadFailed: "No se pudo cargar la lista. Inténtalo de nuevo.",
  emptyArtists: "Añade tu primer artista.",
  emptyGifts: "Añade tu primer regalo.",
  emptyPosters: "Todavía no hay imágenes anteriores.",
  current: "Actual",
  history: "Imágenes anteriores",
  restore: "Restaurar esta imagen",
  previous: "Anterior",
  next: "Siguiente",
  search: "Buscar",
  searchPlaceholder: "Buscar por nombre",
  noResults: "No hay resultados coincidentes.",
  checkingSession: "Abriendo tu espacio…",
  sessionMissing: "La sesión no está disponible. Vuelve a conectar.",
  reconnect: "Volver a conectar",
  inventory: "Disponibilidad",
  inventoryPolicyLocked:
    "Ya existen registros de inventario, por lo que debe mantenerse esta forma de venta. Puedes editar la cantidad y los demás datos del regalo.",
  madeToOrder: "Preparar por pedido",
  tracked: "Existencias limitadas",
  preorder: "Preventa",
  quantity: "Cantidad disponible",
  location: "Ubicación de existencias",
  market: "Mercado",
  currency: "Moneda",
  noMarket: "Configura el mercado y la moneda antes de fijar el precio.",
  noLocation: "No hay ubicaciones de existencias disponibles.",
  viewStorefront: "Ver en el sitio",
  imageFormat: "Elige una imagen JPEG, PNG o WebP.",
  imageEmpty: "El archivo está vacío. Elige otra imagen.",
  imageRequired: "Elige una imagen primero.",
  required: "Completa este campo.",
  invalidPrice: "Introduce un precio válido para esta moneda.",
  invalidQuantity: "Introduce un número entero igual o mayor que cero.",
  sourceTooSmall:
    "La imagen es demasiado pequeña. Elige un original más grande.",
  forbidden: "No tienes permiso para publicar este cambio.",
  conflict: "El contenido ha cambiado. Recarga la lista antes de editar.",
  network:
    "Se interrumpió la conexión. Reintenta para continuar esta actualización.",
  failedProcessing:
    "No se pudo completar la actualización. Inténtalo de nuevo.",
  reloadList: "Recargar lista",
  untitled: "Sin nombre",
  virtual: "Regalo virtual",
  physical: "Regalo físico",
  wish: "Regalo de deseo",
  merchandise: "Artículos de colección",
  other: "Otros",
  flowers: "Flores",
  food: "Alimentos",
  beauty: "Belleza",
  accessory: "Accesorios",
  posterUnavailable:
    "Publica un artista y la página de inicio antes de cambiar la imagen.",
  original: "Contenido original",
  pendingUpdates: "Actualizaciones en curso",
  draft: "Borrador",
  paused: "En pausa",
  archived: "Archivado",
  imageUnavailable: "Imagen no disponible",
  readOnly: "Solo lectura",
} satisfies ManagementCopy;
