import type { ManagementCopy } from "./copy";
export const copy = {
  interfaceLanguage: "界面语言",
  discardEdits: "放弃尚未保存的修改并离开此页？",
  adjustFocus: "调整图片焦点",
  focusHint:
    "在原图上点击需要保留的主体。方向键可微调，Shift + 方向键可大幅移动。",
  focusHorizontal: "水平焦点",
  focusVertical: "垂直焦点",
  resetFocus: "重置焦点",
  previewPortrait: "艺人肖像",
  previewDesktop: "电脑海报",
  previewMobile: "手机海报",
  previewGift: "礼物图片",
  originalLoading: "正在加载原图…",
  originalUnavailable: "原图加载失败，请重试。你的修改已保留。",
  reuploadRequired: "请重新上传原图后调整这张图片。",
  imageUnchanged: "请选择新图片或调整焦点后再发布。",

  login: "登录",
  loginHint: "登录后管理艺人、礼物和海报。",
  loginFailed: "登录未成功，请重试。",
  sessionExpired: "会话已结束，请重新登录。",
  sessionUnavailable: "暂时无法检查会话，请重试。",
  logout: "退出登录",
  logoutFailed: "暂时无法确认退出，请重试。",

  center: "管理中心",
  artists: "艺人",
  gifts: "礼物",
  posters: "首页海报",
  addArtist: "添加艺人",
  addGift: "添加礼物",
  replacePoster: "替换海报",
  back: "返回列表",
  edit: "编辑",
  save: "保存并显示",
  addAndPublish: "添加并显示",
  upload: "选择图片",
  changeImage: "更换图片",
  imageHint: "支持 JPEG、PNG、WebP。前台会按各展示位的比例裁切铺满。",
  imageBestSize: "建议至少 {width} × {height} 像素。",
  imageTipArtist: "人物脸部放在画面上部。",
  imageTipGift: "礼物放在画面中间。",
  imageTipPoster: "主体放在画面中间，手机端只显示中间部分。",
  imageTooSmall:
    "这张图为 {width} × {height} 像素，小于建议尺寸，在大屏上可能发虚。",
  name: "名称",
  description: "描述",
  price: "售价",
  kind: "礼物类型",
  category: "商品分类",
  options: "更多设置",
  sourceLanguage: "内容语言",
  rightsNotice: "提交即确认你有权使用并发布这些图片及内容。",
  uploading: "正在上传图片…",
  processing: "正在处理并发布…",
  published: "已显示",
  retry: "重试",
  dismiss: "知道了",
  loadFailed: "列表暂时无法加载，请重试。",
  emptyArtists: "添加第一位艺人。",
  emptyGifts: "添加第一件礼物。",
  emptyPosters: "暂无历史海报。",
  current: "当前使用",
  history: "历史海报",
  restore: "恢复此图",
  previous: "上一页",
  next: "下一页",
  search: "搜索",
  searchPlaceholder: "按名称搜索",
  noResults: "没有找到匹配内容。",
  checkingSession: "正在打开管理中心…",
  sessionMissing: "当前会话不可用，请重新连接。",
  reconnect: "重新连接",
  inventory: "售卖方式",
  inventoryPolicyLocked:
    "已有库存记录，售卖方式需保持不变；仍可修改数量及其他礼物信息。",
  madeToOrder: "按单准备，可重复售卖",
  tracked: "限量现货",
  preorder: "预售",
  quantity: "现货数量",
  location: "库存位置",
  market: "销售地区",
  currency: "币种",
  noMarket: "请先配置销售地区和币种，再设置售价。",
  noLocation: "暂无可用的库存位置。",
  viewStorefront: "查看前台",
  imageFormat: "请选择 JPEG、PNG 或 WebP 图片。",
  imageEmpty: "文件为空，请重新选择图片。",
  imageRequired: "请先选择图片。",
  required: "请填写此项。",
  invalidPrice: "请填写符合当前币种精度的售价。",
  invalidQuantity: "请填写不小于零的整数。",
  sourceTooSmall: "图片尺寸不足，请选择更大的原图。",
  forbidden: "当前账号没有发布此内容的权限。",
  conflict: "内容已被更新，请刷新列表后重新编辑。",
  network: "连接中断，重试可继续本次更新。",
  failedProcessing: "本次更新未能完成，请重试。",
  reloadList: "刷新列表",
  untitled: "未命名",
  virtual: "虚拟礼物",
  physical: "实体礼物",
  wish: "心愿礼物",
  merchandise: "周边礼物",
  other: "其他",
  flowers: "鲜花",
  food: "食品",
  beauty: "美妆",
  accessory: "配饰",
  posterUnavailable: "请先添加艺人并配置首页，再替换海报。",
  original: "原文",
  pendingUpdates: "正在更新",
  draft: "草稿",
  paused: "已暂停",
  archived: "已归档",
  imageUnavailable: "图片暂不可用",
  readOnly: "暂不可编辑",
  deleteTitle: "永久删除",
  deleteWarning:
    "删除后将从网站和此列表中移除，无法恢复。已有订单的记录不受影响。",
  deleteTypeName: "请输入完整名称以确认",
  deleteConfirm: "永久删除",
  deleted: "已删除，网站上不再显示。",
  posterDelete: "删除",
  posterDeleteWarning:
    "从历史中删除这张海报？删除后无法恢复，首页当前海报不受影响。",
  posterDeleteConfirm: "确认删除",
  posterDeleteCancel: "保留",
  posterDeleted: "海报已删除，首页不受影响。",
  assignment: "归属经纪人",
  assignmentNone: "未分配",
  assignmentStudio: "未分配（超管直管）",
  assignmentAll: "全部艺人",
  assignmentFilter: "按归属筛选",
  assignmentInactive: "{name}（已停用）",
  assignmentImmediate: "修改后立即生效，无需点击保存。",
  assignmentOnCreate: "艺人添加后立即归到该经纪人名下。",
  assignmentSaved: "归属已更新。",
  assignmentFailed: "归属未能保存，请重试。",
  assignmentStale: "归属已被其他人修改，请返回列表后重新打开。",
  assignmentMissed: "艺人已添加，但归属经纪人未保存。请打开该艺人重新选择。",
} satisfies ManagementCopy;
