import type { ManagementCopy } from "./copy";
export const copy = {
  interfaceLanguage: "Idioma da interface",
  discardEdits: "Descartar as alterações não guardadas e sair desta página?",
  adjustFocus: "Ajustar o foco do recorte",
  focusHint:
    "Escolha o motivo na foto original. Use as setas para pequenos movimentos ou Shift + seta para movimentos maiores.",
  focusHorizontal: "Foco horizontal",
  focusVertical: "Foco vertical",
  resetFocus: "Repor foco",
  previewPortrait: "Retrato",
  previewDesktop: "Banner para computador",
  previewMobile: "Banner para telemóvel",
  previewGift: "Foto do presente",
  originalLoading: "A carregar a foto original…",
  originalUnavailable:
    "Não foi possível carregar a foto original. Tente novamente; as alterações foram mantidas.",
  reuploadRequired: "Envie novamente a foto original para ajustar esta imagem.",
  imageUnchanged: "Escolha uma nova foto ou ajuste o foco antes de publicar.",

  login: "Entrar",
  loginHint: "Entre para gerenciar artistas, presentes e cartazes.",
  loginFailed: "Não foi possível entrar. Tente novamente.",
  sessionExpired: "Sua sessão terminou. Entre novamente para continuar.",
  sessionUnavailable: "Não foi possível verificar sua sessão. Tente novamente.",
  logout: "Sair",
  logoutFailed: "Não foi possível confirmar a saída. Tente novamente.",

  center: "Centro de gestão",
  artists: "Artistas",
  gifts: "Presentes",
  posters: "Imagem inicial",
  addArtist: "Adicionar artista",
  addGift: "Adicionar presente",
  replacePoster: "Substituir imagem",
  back: "Voltar à lista",
  edit: "Editar",
  save: "Guardar e publicar",
  addAndPublish: "Adicionar e publicar",
  upload: "Escolher imagem",
  changeImage: "Alterar imagem",
  imageHint:
    "JPEG, PNG ou WebP. A foto é recortada para preencher cada espaço de exibição.",
  imageBestSize: "Recomendado: pelo menos {width} × {height} px.",
  imageTipArtist: "Mantenha o rosto na parte superior.",
  imageTipGift: "Mantenha o presente no centro.",
  imageTipPoster:
    "Mantenha o assunto no centro; no celular aparece só a parte central.",
  imageTooSmall:
    "Esta imagem tem {width} × {height} px, abaixo do recomendado, e pode ficar desfocada em telas grandes.",
  name: "Nome",
  description: "Descrição",
  price: "Preço",
  kind: "Tipo de presente",
  category: "Categoria",
  options: "Mais opções",
  sourceLanguage: "Idioma do conteúdo",
  rightsNotice:
    "Ao enviar, confirma que pode publicar estas imagens e este conteúdo.",
  uploading: "A carregar imagem…",
  processing: "A processar e publicar…",
  published: "Publicado",
  retry: "Tentar novamente",
  dismiss: "Fechar",
  loadFailed: "Não foi possível carregar a lista. Tente novamente.",
  emptyArtists: "Adicione o primeiro artista.",
  emptyGifts: "Adicione o primeiro presente.",
  emptyPosters: "Ainda não existem imagens anteriores.",
  current: "Atual",
  history: "Imagens anteriores",
  restore: "Restaurar esta imagem",
  previous: "Anterior",
  next: "Seguinte",
  search: "Pesquisar",
  searchPlaceholder: "Pesquisar por nome",
  noResults: "Não foram encontrados resultados.",
  checkingSession: "A abrir o espaço de gestão…",
  sessionMissing: "A sessão não está disponível. Volte a ligar.",
  reconnect: "Voltar a ligar",
  inventory: "Disponibilidade",
  inventoryPolicyLocked:
    "Já existem registos de stock, pelo que esta forma de venda deve manter-se. Pode editar a quantidade e os restantes dados do presente.",
  madeToOrder: "Preparar por encomenda",
  tracked: "Stock limitado",
  preorder: "Pré-venda",
  quantity: "Quantidade disponível",
  location: "Local de stock",
  market: "Mercado",
  currency: "Moeda",
  noMarket: "Configure o mercado e a moeda antes de definir o preço.",
  noLocation: "Não existem locais de stock disponíveis.",
  viewStorefront: "Ver no site",
  imageFormat: "Escolha uma imagem JPEG, PNG ou WebP.",
  imageEmpty: "O ficheiro está vazio. Escolha outra imagem.",
  imageRequired: "Escolha primeiro uma imagem.",
  required: "Preencha este campo.",
  invalidPrice: "Introduza um preço válido para esta moeda.",
  invalidQuantity: "Introduza um número inteiro igual ou superior a zero.",
  sourceTooSmall: "A imagem é demasiado pequena. Escolha um original maior.",
  forbidden: "Não tem permissão para publicar esta alteração.",
  conflict: "O conteúdo foi alterado. Atualize a lista antes de editar.",
  network:
    "A ligação foi interrompida. Tente novamente para continuar esta atualização.",
  failedProcessing: "Não foi possível concluir a atualização. Tente novamente.",
  reloadList: "Atualizar lista",
  untitled: "Sem nome",
  virtual: "Presente virtual",
  physical: "Presente físico",
  wish: "Presente de desejo",
  merchandise: "Artigos de coleção",
  other: "Outros",
  flowers: "Flores",
  food: "Alimentos",
  beauty: "Beleza",
  accessory: "Acessórios",
  posterUnavailable:
    "Publique um artista e a página inicial antes de alterar a imagem.",
  original: "Conteúdo original",
  pendingUpdates: "Atualizações em curso",
  draft: "Rascunho",
  paused: "Em pausa",
  archived: "Arquivado",
  imageUnavailable: "Imagem indisponível",
  readOnly: "Apenas leitura",
  deleteTitle: "Excluir definitivamente",
  deleteWarning:
    "Será removido do site e desta lista. Não é possível desfazer. Os pedidos existentes mantêm seu registro.",
  deleteTypeName: "Digite o nome exato para confirmar",
  deleteConfirm: "Excluir definitivamente",
  deleted: "Excluído. Não aparece mais no site.",
} satisfies ManagementCopy;
