export const copy = {
  login: "Sign in",
  loginHint: "Sign in to manage artists, gifts and posters.",
  loginFailed: "We could not sign you in. Please try again.",
  sessionExpired: "Your session has ended. Sign in again to continue.",
  sessionUnavailable: "We could not check your session. Please try again.",
  logout: "Sign out",
  logoutFailed: "We could not confirm sign-out. Please try again.",

  center: "Management center",
  artists: "Artists",
  gifts: "Gifts",
  posters: "Homepage poster",
  addArtist: "Add artist",
  addGift: "Add gift",
  replacePoster: "Replace poster",
  back: "Back to list",
  edit: "Edit",
  save: "Save and publish",
  addAndPublish: "Add and publish",
  upload: "Choose photo",
  changeImage: "Change photo",
  imageHint: "JPEG, PNG or WebP. Your photo keeps its proportions.",
  name: "Name",
  description: "Description",
  price: "Price",
  kind: "Gift type",
  category: "Category",
  options: "More settings",
  sourceLanguage: "Content language",
  rightsNotice:
    "By submitting, you confirm that you may publish these photos and this content.",
  uploading: "Uploading photo…",
  processing: "Preparing your update…",
  published: "Published",
  retry: "Try again",
  loadFailed: "We could not load the list. Try again.",
  emptyArtists: "Add your first artist.",
  emptyGifts: "Add your first gift.",
  emptyPosters: "No previous posters yet.",
  current: "Current",
  history: "Previous posters",
  restore: "Restore this image",
  previous: "Previous",
  next: "Next",
  search: "Search",
  searchPlaceholder: "Search by name",
  noResults: "No matching results.",
  checkingSession: "Opening your workspace…",
  sessionMissing: "Your session is unavailable. Reconnect to continue.",
  reconnect: "Reconnect",
  inventory: "Availability",
  inventoryPolicyLocked:
    "Inventory records already exist, so this selling policy must stay the same. You can still edit the quantity and other gift details.",
  madeToOrder: "Prepare for each order",
  tracked: "Limited stock",
  preorder: "Preorder",
  quantity: "Available quantity",
  location: "Stock location",
  market: "Market",
  currency: "Currency",
  noMarket: "Set up a selling market and currency before adding a price.",
  noLocation: "No stock location is available.",
  viewStorefront: "View on website",
  imageFormat: "Choose a JPEG, PNG or WebP image.",
  imageEmpty: "This file is empty. Choose another photo.",
  imageRequired: "Choose a photo first.",
  required: "Complete this field.",
  invalidPrice: "Enter a valid price for this currency.",
  invalidQuantity: "Enter a whole number of zero or more.",
  sourceTooSmall: "This photo is too small. Choose a larger original.",
  forbidden: "You do not have permission to publish this change.",
  conflict:
    "This content changed elsewhere. Reload the list before editing again.",
  network: "Connection interrupted. Try again to continue the same update.",
  failedProcessing: "This update could not be completed. Please try again.",
  reloadList: "Reload list",
  untitled: "Untitled",
  virtual: "Virtual gift",
  physical: "Physical gift",
  wish: "Wish gift",
  merchandise: "Merchandise",
  other: "Other",
  flowers: "Flowers",
  food: "Food",
  beauty: "Beauty",
  accessory: "Accessories",
  posterUnavailable:
    "Publish an artist and homepage before replacing the poster.",
  original: "Original content",
  pendingUpdates: "Updates in progress",
  draft: "Draft",
  paused: "Paused",
  archived: "Archived",
  imageUnavailable: "Image unavailable",
  readOnly: "View only",
};
