import type { ManagementCopy } from "./copy";
export const copy = {
  interfaceLanguage: "表示言語",
  discardEdits: "未保存の変更を破棄して、このページを離れますか？",
  adjustFocus: "画像の焦点を調整",
  focusHint:
    "元の写真で残したい被写体を選びます。矢印キーで微調整、Shift + 矢印キーで大きく移動できます。",
  focusHorizontal: "横方向の焦点",
  focusVertical: "縦方向の焦点",
  resetFocus: "焦点をリセット",
  previewPortrait: "ポートレート",
  previewDesktop: "パソコン用バナー",
  previewMobile: "スマートフォン用バナー",
  previewGift: "ギフト画像",
  originalLoading: "元の写真を読み込み中…",
  originalUnavailable:
    "元の写真を読み込めませんでした。変更は保持されています。再試行してください。",
  reuploadRequired:
    "この画像を調整するには、元の写真を再アップロードしてください。",
  imageUnchanged: "新しい写真を選ぶか焦点を調整してから公開してください。",

  login: "ログイン",
  loginHint: "ログインしてアーティスト、ギフト、ポスターを管理します。",
  loginFailed: "ログインできませんでした。もう一度お試しください。",
  sessionExpired: "セッションが終了しました。再度ログインしてください。",
  sessionUnavailable:
    "セッションを確認できませんでした。もう一度お試しください。",
  logout: "ログアウト",
  logoutFailed: "ログアウトを確認できませんでした。もう一度お試しください。",

  center: "管理センター",
  artists: "アーティスト",
  gifts: "ギフト",
  posters: "トップ画像",
  addArtist: "アーティストを追加",
  addGift: "ギフトを追加",
  replacePoster: "画像を変更",
  back: "一覧に戻る",
  edit: "編集",
  save: "保存して公開",
  addAndPublish: "追加して公開",
  upload: "画像を選ぶ",
  changeImage: "画像を変更",
  imageHint:
    "JPEG・PNG・WebPに対応。各表示枠いっぱいに合わせて切り抜かれます。",
  imageBestSize: "推奨サイズは {width} × {height} px 以上です。",
  imageTipArtist: "顔は画像の上部に配置してください。",
  imageTipGift: "ギフトは画像の中央に配置してください。",
  imageTipPoster:
    "被写体は中央に。スマートフォンでは中央部分のみ表示されます。",
  imageTooSmall:
    "この画像は {width} × {height} px で推奨サイズより小さいため、大きな画面ではぼやけて見える場合があります。",
  name: "名前",
  description: "説明",
  price: "価格",
  kind: "ギフトの種類",
  category: "カテゴリー",
  options: "その他の設定",
  sourceLanguage: "内容の言語",
  rightsNotice:
    "送信すると、画像と内容を公開する権利があることを確認したものとします。",
  uploading: "画像をアップロード中…",
  processing: "処理して公開しています…",
  published: "公開済み",
  retry: "再試行",
  dismiss: "閉じる",
  loadFailed: "一覧を読み込めませんでした。再試行してください。",
  emptyArtists: "最初のアーティストを追加しましょう。",
  emptyGifts: "最初のギフトを追加しましょう。",
  emptyPosters: "過去の画像はまだありません。",
  current: "使用中",
  history: "過去の画像",
  restore: "この画像に戻す",
  previous: "前へ",
  next: "次へ",
  search: "検索",
  searchPlaceholder: "名前で検索",
  noResults: "一致する内容がありません。",
  checkingSession: "管理画面を開いています…",
  sessionMissing: "セッションを利用できません。再接続してください。",
  reconnect: "再接続",
  inventory: "販売方式",
  inventoryPolicyLocked:
    "在庫の記録があるため、販売方式は変更できません。数量やその他のギフト情報は引き続き編集できます。",
  madeToOrder: "注文ごとに準備",
  tracked: "数量限定の在庫",
  preorder: "予約販売",
  quantity: "在庫数",
  location: "在庫の保管場所",
  market: "販売地域",
  currency: "通貨",
  noMarket: "価格を設定する前に販売地域と通貨を設定してください。",
  noLocation: "利用可能な在庫保管場所がありません。",
  viewStorefront: "サイトで確認",
  imageFormat: "JPEG・PNG・WebP画像を選んでください。",
  imageEmpty: "ファイルが空です。別の画像を選んでください。",
  imageRequired: "画像を選んでください。",
  required: "この項目を入力してください。",
  invalidPrice: "この通貨で有効な価格を入力してください。",
  invalidQuantity: "0以上の整数を入力してください。",
  sourceTooSmall: "画像が小さすぎます。大きい元画像を選んでください。",
  forbidden: "この変更を公開する権限がありません。",
  conflict: "内容が更新されました。一覧を再読み込みして編集してください。",
  network: "接続が中断されました。再試行して同じ更新を続けられます。",
  failedProcessing: "更新を完了できませんでした。再試行してください。",
  reloadList: "一覧を再読み込み",
  untitled: "名称未設定",
  virtual: "バーチャルギフト",
  physical: "実物のギフト",
  wish: "ウィッシュギフト",
  merchandise: "グッズ",
  other: "その他",
  flowers: "花",
  food: "食品",
  beauty: "美容",
  accessory: "アクセサリー",
  posterUnavailable:
    "画像を変更する前にアーティストとトップページを設定してください。",
  original: "原文",
  pendingUpdates: "更新中",
  draft: "下書き",
  paused: "一時停止",
  archived: "アーカイブ済み",
  imageUnavailable: "画像を表示できません",
  readOnly: "閲覧のみ",
  deleteTitle: "完全に削除",
  deleteWarning:
    "サイトとこの一覧から削除され、元に戻せません。既存の注文の記録はそのまま残ります。",
  deleteTypeName: "確認のため名前を正確に入力してください",
  deleteConfirm: "完全に削除",
  deleted: "削除しました。サイトには表示されなくなりました。",
  posterDelete: "削除",
  posterDeleteWarning:
    "この画像を履歴から削除しますか？元に戻せません。現在のトップ画像には影響しません。",
  posterDeleteConfirm: "削除する",
  posterDeleteCancel: "残す",
  posterDeleted: "画像を削除しました。トップページは変わりません。",
} satisfies ManagementCopy;
