import type { ManagementCopy } from "./copy";
export const copy = {
  login: "Đăng nhập",
  loginHint: "Đăng nhập để quản lý nghệ sĩ, quà tặng và áp phích.",
  loginFailed: "Không thể đăng nhập. Vui lòng thử lại.",
  sessionExpired: "Phiên đã kết thúc. Vui lòng đăng nhập lại.",
  sessionUnavailable: "Chưa thể kiểm tra phiên. Vui lòng thử lại.",
  logout: "Đăng xuất",
  logoutFailed: "Chưa thể xác nhận đăng xuất. Vui lòng thử lại.",

  center: "Trung tâm quản lý",
  artists: "Nghệ sĩ",
  gifts: "Quà tặng",
  posters: "Ảnh trang chủ",
  addArtist: "Thêm nghệ sĩ",
  addGift: "Thêm quà tặng",
  replacePoster: "Thay ảnh",
  back: "Về danh sách",
  edit: "Chỉnh sửa",
  save: "Lưu và hiển thị",
  addAndPublish: "Thêm và hiển thị",
  upload: "Chọn ảnh",
  changeImage: "Đổi ảnh",
  imageHint: "JPEG, PNG hoặc WebP. Giữ nguyên tỷ lệ ảnh.",
  name: "Tên",
  description: "Mô tả",
  price: "Giá bán",
  kind: "Loại quà tặng",
  category: "Danh mục",
  options: "Cài đặt thêm",
  sourceLanguage: "Ngôn ngữ nội dung",
  rightsNotice:
    "Khi gửi, bạn xác nhận có quyền sử dụng và đăng các ảnh cùng nội dung này.",
  uploading: "Đang tải ảnh lên…",
  processing: "Đang xử lý và đăng…",
  published: "Đã hiển thị",
  retry: "Thử lại",
  loadFailed: "Chưa tải được danh sách. Vui lòng thử lại.",
  emptyArtists: "Thêm nghệ sĩ đầu tiên.",
  emptyGifts: "Thêm quà tặng đầu tiên.",
  emptyPosters: "Chưa có ảnh trước đây.",
  current: "Đang dùng",
  history: "Ảnh trước đây",
  restore: "Khôi phục ảnh này",
  previous: "Trang trước",
  next: "Trang sau",
  search: "Tìm kiếm",
  searchPlaceholder: "Tìm theo tên",
  noResults: "Không có kết quả phù hợp.",
  checkingSession: "Đang mở trung tâm quản lý…",
  sessionMissing: "Phiên làm việc không khả dụng. Vui lòng kết nối lại.",
  reconnect: "Kết nối lại",
  inventory: "Hình thức bán",
  inventoryPolicyLocked:
    "Đã có dữ liệu tồn kho nên cần giữ nguyên hình thức bán. Bạn vẫn có thể sửa số lượng và các thông tin khác của quà tặng.",
  madeToOrder: "Chuẩn bị theo đơn, có thể bán nhiều lần",
  tracked: "Hàng có số lượng giới hạn",
  preorder: "Đặt trước",
  quantity: "Số lượng có sẵn",
  location: "Vị trí kho",
  market: "Thị trường",
  currency: "Tiền tệ",
  noMarket: "Hãy thiết lập thị trường và tiền tệ trước khi đặt giá.",
  noLocation: "Chưa có vị trí kho khả dụng.",
  viewStorefront: "Xem trên trang web",
  imageFormat: "Vui lòng chọn ảnh JPEG, PNG hoặc WebP.",
  imageEmpty: "Tệp này trống. Vui lòng chọn ảnh khác.",
  imageRequired: "Vui lòng chọn ảnh trước.",
  required: "Vui lòng điền mục này.",
  invalidPrice: "Nhập giá hợp lệ theo độ chính xác của tiền tệ này.",
  invalidQuantity: "Nhập số nguyên không nhỏ hơn không.",
  sourceTooSmall: "Ảnh quá nhỏ. Hãy chọn ảnh gốc lớn hơn.",
  forbidden: "Tài khoản này không có quyền đăng thay đổi.",
  conflict: "Nội dung đã thay đổi. Tải lại danh sách trước khi sửa.",
  network: "Kết nối bị gián đoạn. Thử lại để tiếp tục cập nhật này.",
  failedProcessing: "Chưa hoàn tất cập nhật. Vui lòng thử lại.",
  reloadList: "Tải lại danh sách",
  untitled: "Chưa đặt tên",
  virtual: "Quà ảo",
  physical: "Quà hiện vật",
  wish: "Quà theo nguyện vọng",
  merchandise: "Quà lưu niệm",
  other: "Khác",
  flowers: "Hoa",
  food: "Thực phẩm",
  beauty: "Làm đẹp",
  accessory: "Phụ kiện",
  posterUnavailable: "Thêm nghệ sĩ và thiết lập trang chủ trước khi thay ảnh.",
  original: "Nội dung gốc",
  pendingUpdates: "Đang cập nhật",
  draft: "Bản nháp",
  paused: "Đã tạm dừng",
  archived: "Đã lưu trữ",
  imageUnavailable: "Ảnh không khả dụng",
  readOnly: "Chỉ xem",
} satisfies ManagementCopy;
