import type { ManagementCopy } from "./copy";
export const copy = {
  allGifts: "Tất cả",
  priceOrder: "Sắp xếp theo giá",
  priceAscending: "Giá từ thấp đến cao",
  priceDescending: "Giá từ cao đến thấp",
  priceUnavailable: "Chưa có giá",
  wishArtist: "Nghệ sĩ nhận quà",
  wishArtistRequired: "Chọn nghệ sĩ nhận món quà theo nguyện vọng này.",
  wishArtistChoose: "Chọn nghệ sĩ này",
  wishArtistChange: "Chọn nghệ sĩ khác",
  wishArtistLocked:
    "Nguyện vọng này đã gắn với nghệ sĩ và không thể đổi người nhận.",
  wishOnlyOnce:
    "Mỗi nguyện vọng chỉ nhận một lượt ủng hộ. Ngừng bán sau khi xác nhận thanh toán.",
  wishArtistUnavailable:
    "Nghệ sĩ này hiện không thể nhận quà theo nguyện vọng.",
  wishAvailable: "Đang chờ ủng hộ",
  wishReserved: "Đang xử lý thanh toán",
  wishSupported: "Đã ủng hộ nguyện vọng",
  wishUnavailable: "Không khả dụng",
  interfaceLanguage: "Ngôn ngữ giao diện",
  discardEdits: "Bỏ các thay đổi chưa lưu và rời trang này?",
  adjustFocus: "Điều chỉnh tiêu điểm ảnh",
  focusHint:
    "Chọn chủ thể cần giữ trên ảnh gốc. Dùng phím mũi tên để dịch chuyển nhỏ hoặc Shift + mũi tên để dịch chuyển lớn.",
  focusHorizontal: "Tiêu điểm ngang",
  focusVertical: "Tiêu điểm dọc",
  resetFocus: "Đặt lại tiêu điểm",
  previewPortrait: "Chân dung",
  previewDesktop: "Ảnh bìa máy tính",
  previewMobile: "Ảnh bìa điện thoại",
  previewGift: "Ảnh quà tặng",
  originalLoading: "Đang tải ảnh gốc…",
  originalUnavailable:
    "Không thể tải ảnh gốc. Hãy thử lại; các thay đổi vẫn được giữ.",
  reuploadRequired: "Hãy tải lại ảnh gốc để điều chỉnh ảnh này.",
  imageUnchanged: "Chọn ảnh mới hoặc điều chỉnh tiêu điểm trước khi đăng.",

  login: "Đăng nhập",
  loginHint: "Đăng nhập để quản lý nghệ sĩ, quà tặng và áp phích.",
  loginFailed: "Không thể đăng nhập. Vui lòng thử lại.",
  sessionExpired: "Phiên đã kết thúc. Vui lòng đăng nhập lại.",
  sessionUnavailable: "Chưa thể kiểm tra phiên. Vui lòng thử lại.",
  logout: "Đăng xuất",
  logoutFailed: "Chưa thể xác nhận đăng xuất. Vui lòng thử lại.",

  center: "Trung tâm quản lý",
  artists: "Nghệ sĩ",
  gifts: "Quà tặng",
  posters: "Ảnh trang chủ",
  addArtist: "Thêm nghệ sĩ",
  addGift: "Thêm quà tặng",
  replacePoster: "Thay ảnh",
  back: "Về danh sách",
  edit: "Chỉnh sửa",
  save: "Lưu và hiển thị",
  addAndPublish: "Thêm và hiển thị",
  upload: "Chọn ảnh",
  changeImage: "Đổi ảnh",
  imageHint:
    "Hỗ trợ JPEG, PNG hoặc WebP. Ảnh sẽ được cắt để lấp đầy từng vị trí hiển thị.",
  imageBestSize: "Nên tối thiểu {width} × {height} px.",
  imageTipArtist: "Đặt khuôn mặt ở phần trên của ảnh.",
  imageTipGift: "Đặt món quà ở giữa ảnh.",
  imageTipPoster: "Đặt chủ thể ở giữa; điện thoại chỉ hiển thị phần giữa.",
  imageTooSmall:
    "Ảnh này {width} × {height} px, nhỏ hơn kích thước khuyến nghị nên có thể bị mờ trên màn hình lớn.",
  name: "Tên",
  description: "Mô tả",
  price: "Giá bán",
  kind: "Loại quà tặng",
  category: "Danh mục",
  options: "Cài đặt thêm",
  sourceLanguage: "Ngôn ngữ nội dung",
  rightsNotice:
    "Khi gửi, bạn xác nhận có quyền sử dụng và đăng các ảnh cùng nội dung này.",
  uploading: "Đang tải ảnh lên…",
  processing: "Đang xử lý và đăng…",
  published: "Đã hiển thị",
  retry: "Thử lại",
  dismiss: "Đóng",
  loadFailed: "Chưa tải được danh sách. Vui lòng thử lại.",
  emptyArtists: "Thêm nghệ sĩ đầu tiên.",
  emptyGifts: "Thêm quà tặng đầu tiên.",
  emptyPosters: "Chưa có ảnh trước đây.",
  current: "Đang dùng",
  history: "Ảnh trước đây",
  restore: "Khôi phục ảnh này",
  previous: "Trang trước",
  next: "Trang sau",
  search: "Tìm kiếm",
  searchPlaceholder: "Tìm theo tên",
  noResults: "Không có kết quả phù hợp.",
  checkingSession: "Đang mở trung tâm quản lý…",
  sessionMissing: "Phiên làm việc không khả dụng. Vui lòng kết nối lại.",
  reconnect: "Kết nối lại",
  inventory: "Hình thức bán",
  inventoryPolicyLocked:
    "Đã có dữ liệu tồn kho nên cần giữ nguyên hình thức bán. Bạn vẫn có thể sửa số lượng và các thông tin khác của quà tặng.",
  madeToOrder: "Chuẩn bị theo đơn, có thể bán nhiều lần",
  tracked: "Hàng có số lượng giới hạn",
  preorder: "Đặt trước",
  quantity: "Số lượng có sẵn",
  location: "Vị trí kho",
  market: "Thị trường",
  currency: "Tiền tệ",
  noMarket: "Hãy thiết lập thị trường và tiền tệ trước khi đặt giá.",
  noLocation: "Chưa có vị trí kho khả dụng.",
  viewStorefront: "Xem trên trang web",
  imageFormat: "Vui lòng chọn ảnh JPEG, PNG hoặc WebP.",
  imageEmpty: "Tệp này trống. Vui lòng chọn ảnh khác.",
  imageRequired: "Vui lòng chọn ảnh trước.",
  required: "Vui lòng điền mục này.",
  invalidPrice: "Nhập giá hợp lệ theo độ chính xác của tiền tệ này.",
  invalidQuantity: "Nhập số nguyên không nhỏ hơn không.",
  sourceTooSmall: "Ảnh quá nhỏ. Hãy chọn ảnh gốc lớn hơn.",
  forbidden: "Tài khoản này không có quyền đăng thay đổi.",
  conflict: "Nội dung đã thay đổi. Tải lại danh sách trước khi sửa.",
  network: "Kết nối bị gián đoạn. Thử lại để tiếp tục cập nhật này.",
  failedProcessing: "Chưa hoàn tất cập nhật. Vui lòng thử lại.",
  reloadList: "Tải lại danh sách",
  untitled: "Chưa đặt tên",
  virtual: "Quà ảo",
  physical: "Quà hiện vật",
  wish: "Quà theo nguyện vọng",
  merchandise: "Quà lưu niệm",
  other: "Khác",
  flowers: "Hoa",
  food: "Thực phẩm",
  beauty: "Làm đẹp",
  accessory: "Phụ kiện",
  posterUnavailable: "Thêm nghệ sĩ và thiết lập trang chủ trước khi thay ảnh.",
  original: "Nội dung gốc",
  pendingUpdates: "Đang cập nhật",
  draft: "Bản nháp",
  paused: "Đã tạm dừng",
  archived: "Đã lưu trữ",
  imageUnavailable: "Ảnh không khả dụng",
  readOnly: "Chỉ xem",
  deleteTitle: "Xóa vĩnh viễn",
  deleteWarning:
    "Mục này sẽ bị gỡ khỏi trang web và khỏi danh sách này, không thể hoàn tác. Các đơn hàng hiện có vẫn giữ nguyên hồ sơ.",
  deleteTypeName: "Nhập chính xác tên để xác nhận",
  deleteConfirm: "Xóa vĩnh viễn",
  deleted: "Đã xóa. Mục này không còn hiển thị trên trang web.",
  posterDelete: "Xóa",
  posterDeleteWarning:
    "Xóa ảnh này khỏi lịch sử? Không thể hoàn tác. Ảnh trang chủ hiện tại không bị ảnh hưởng.",
  posterDeleteConfirm: "Xác nhận xóa",
  posterDeleteCancel: "Giữ lại",
  posterDeleted: "Đã xóa ảnh. Trang chủ không thay đổi.",
  assignment: "Quản lý nghệ sĩ",
  assignmentNone: "Chưa phân công",
  assignmentStudio: "Chưa phân công (studio trực tiếp quản lý)",
  assignmentAll: "Tất cả nghệ sĩ",
  assignmentFilter: "Hiển thị nghệ sĩ của",
  assignmentInactive: "{name} (đã ngừng hoạt động)",
  assignmentImmediate: "Thay đổi ở đây có hiệu lực ngay, không cần bấm lưu.",
  assignmentOnCreate: "Nghệ sĩ sẽ thuộc về quản lý này ngay khi được thêm.",
  assignmentSaved: "Đã cập nhật quản lý.",
  assignmentFailed: "Không lưu được quản lý. Vui lòng thử lại.",
  assignmentStale:
    "Người khác đã đổi quản lý. Hãy quay lại danh sách và mở lại nghệ sĩ.",
  assignmentMissed:
    "Đã thêm nghệ sĩ nhưng chưa lưu được quản lý. Hãy mở nghệ sĩ và chọn lại quản lý.",
} satisfies ManagementCopy;
