import type { SupportedLocale } from "@fan-support/contracts";
import type { SectionId } from "./model";

const en = {
  reset: "Use default layout",
  title: "Storefront",
  intro: "Arrange your homepage, preview it, then publish when ready.",
  sectionTitle: "Page sections",
  shown: "Show",
  required: "Always shown",
  moveUp: "Move up",
  moveDown: "Move down",
  preview: "Preview",
  previewHint:
    "Published content, with your layout changes. Browsing and purchases are disabled here.",
  previewUnavailable:
    "Preview is unavailable until the storefront address is configured.",
  previewFailed: "The preview could not load. Try again.",
  mobile: "Phone",
  desktop: "Desktop",
  save: "Save draft",
  publish: "Publish",
  history: "Publication history",
  restore: "Restore",
  noHistory: "Your published layouts will appear here.",
  loading: "Loading…",
  saved: "Draft saved",
  published: "Layout published",
  restored: "Layout restored",
  unsaved: "Unsaved changes",
  draft: "Saved draft",
  live: "Published layout",
  error:
    "This change could not be confirmed. Your edits are still here. Try again.",
  conflict:
    "Another operator changed this layout. Reload the latest version before continuing.",
  forbidden: "Your account does not have permission for this action.",
  reload: "Reload",
  discard: "Leave and discard your unsaved layout changes?",
  cancel: "Cancel",
  restoreConfirm:
    "Restore this layout? This replaces the current layout and draft. Images, gifts and orders stay as they are.",
  previous: "Previous",
  next: "Next",
  liveLink: "Open storefront",
  version: "Version",
};
export type DecorationCopy = { [K in keyof typeof en]: string } & {
  sections: Record<SectionId, string>;
};
export function decorationCopy(locale: SupportedLocale): DecorationCopy {
  switch (locale) {
    case "en":
      return {
        ...en,
        sections: {
          HERO: "Main poster",
          KINDS: "Gift categories",
          ARTISTS: "Artists",
          GIFTS: "Gifts",
          POLICIES: "Policy links",
          HOW_IT_WORKS: "How it works",
          STUDIO_PROMISE: "Studio promise",
          FINAL_CTA: "Final invitation",
        },
      };
    case "zh-CN":
      return {
        reset: "使用默认布局",
        title: "店铺装修",
        intro: "调整首页顺序和显示内容，预览满意后再发布。",
        sectionTitle: "首页区块",
        shown: "显示",
        required: "始终显示",
        moveUp: "上移",
        moveDown: "下移",
        preview: "预览",
        previewHint: "使用已发布的内容预览当前布局，预览中无法跳转或购买。",
        previewUnavailable: "配置商城地址后即可使用预览。",
        previewFailed: "预览暂时无法加载，请重试。",
        mobile: "手机",
        desktop: "电脑",
        save: "保存草稿",
        publish: "发布",
        history: "发布历史",
        restore: "恢复",
        noHistory: "发布后的布局会保存在这里。",
        loading: "正在加载…",
        saved: "草稿已保存",
        published: "布局已发布",
        restored: "布局已恢复",
        unsaved: "有未保存的修改",
        draft: "已保存的草稿",
        live: "已发布布局",
        error: "暂时无法确认操作结果，修改仍已保留，请重试。",
        conflict: "其他人员已更新布局，请重新加载最新版本后继续。",
        forbidden: "当前账号没有此操作权限。",
        reload: "重新加载",
        discard: "离开并放弃尚未保存的布局修改？",
        cancel: "取消",
        restoreConfirm:
          "恢复这个布局？当前布局和草稿将被替换，图片、礼物和订单保持原样。",
        previous: "上一页",
        next: "下一页",
        liveLink: "查看商城",
        version: "版本",
        sections: {
          HERO: "首页海报",
          KINDS: "礼物分类",
          ARTISTS: "艺人展示",
          GIFTS: "礼物展示",
          POLICIES: "政策链接",
          HOW_IT_WORKS: "送礼流程",
          STUDIO_PROMISE: "工作室承诺",
          FINAL_CTA: "末尾引导",
        },
      };
    case "ja":
      return {
        reset: "標準レイアウトに戻す",
        title: "ストアのデザイン",
        intro: "ホームの表示と順序を調整し、確認してから公開します。",
        sectionTitle: "ページのセクション",
        shown: "表示",
        required: "常に表示",
        moveUp: "上へ",
        moveDown: "下へ",
        preview: "プレビュー",
        previewHint:
          "公開中のコンテンツでレイアウトを確認できます。ページ移動や購入はできません。",
        previewUnavailable: "ストアのアドレスを設定するとプレビューできます。",
        previewFailed: "プレビューを読み込めませんでした。再試行してください。",
        mobile: "スマートフォン",
        desktop: "パソコン",
        save: "下書きを保存",
        publish: "公開",
        history: "公開履歴",
        restore: "復元",
        noHistory: "公開したレイアウトがここに表示されます。",
        loading: "読み込み中…",
        saved: "下書きを保存しました",
        published: "公開しました",
        restored: "復元しました",
        unsaved: "未保存の変更",
        draft: "保存済みの下書き",
        live: "公開中のレイアウト",
        error:
          "結果を確認できませんでした。変更は保持されています。再試行してください。",
        conflict: "他の担当者が更新しました。最新の内容を読み込んでください。",
        forbidden: "この操作の権限がありません。",
        reload: "再読み込み",
        discard: "未保存の変更を破棄して移動しますか？",
        cancel: "キャンセル",
        restoreConfirm:
          "このレイアウトを復元しますか？現在のレイアウトと下書きが置き換わります。画像、ギフト、注文は変わりません。",
        previous: "前へ",
        next: "次へ",
        liveLink: "ストアを開く",
        version: "バージョン",
        sections: {
          HERO: "メインポスター",
          KINDS: "ギフトの種類",
          ARTISTS: "アーティスト",
          GIFTS: "ギフト",
          POLICIES: "ポリシーリンク",
          HOW_IT_WORKS: "贈り方",
          STUDIO_PROMISE: "スタジオの約束",
          FINAL_CTA: "最後のご案内",
        },
      };
    case "th":
      return {
        reset: "ใช้รูปแบบเริ่มต้น",
        title: "ตกแต่งร้าน",
        intro: "ปรับลำดับและการแสดงผลหน้าแรก ดูตัวอย่าง แล้วจึงเผยแพร่",
        sectionTitle: "ส่วนต่าง ๆ ของหน้า",
        shown: "แสดง",
        required: "แสดงเสมอ",
        moveUp: "เลื่อนขึ้น",
        moveDown: "เลื่อนลง",
        preview: "ตัวอย่าง",
        previewHint:
          "ดูเนื้อหาที่เผยแพร่แล้วพร้อมรูปแบบใหม่ ไม่สามารถเปลี่ยนหน้าหรือซื้อสินค้าในตัวอย่างได้",
        previewUnavailable: "ตั้งค่าที่อยู่ร้านเพื่อดูตัวอย่าง",
        previewFailed: "โหลดตัวอย่างไม่สำเร็จ โปรดลองอีกครั้ง",
        mobile: "มือถือ",
        desktop: "คอมพิวเตอร์",
        save: "บันทึกฉบับร่าง",
        publish: "เผยแพร่",
        history: "ประวัติการเผยแพร่",
        restore: "คืนค่า",
        noHistory: "รูปแบบที่เผยแพร่แล้วจะแสดงที่นี่",
        loading: "กำลังโหลด…",
        saved: "บันทึกฉบับร่างแล้ว",
        published: "เผยแพร่รูปแบบแล้ว",
        restored: "คืนค่ารูปแบบแล้ว",
        unsaved: "มีการแก้ไขที่ยังไม่ได้บันทึก",
        draft: "ฉบับร่างที่บันทึกแล้ว",
        live: "รูปแบบที่เผยแพร่",
        error: "ยังยืนยันผลไม่ได้ การแก้ไขยังอยู่ โปรดลองอีกครั้ง",
        conflict: "มีผู้ดูแลคนอื่นแก้ไขรูปแบบนี้ โปรดโหลดเวอร์ชันล่าสุดก่อน",
        forbidden: "บัญชีนี้ไม่มีสิทธิ์ดำเนินการ",
        reload: "โหลดใหม่",
        discard: "ออกจากหน้านี้และละทิ้งการแก้ไขที่ยังไม่บันทึกหรือไม่?",
        cancel: "ยกเลิก",
        restoreConfirm:
          "คืนค่ารูปแบบนี้หรือไม่? รูปแบบและฉบับร่างปัจจุบันจะถูกแทนที่ รูปภาพ ของขวัญ และคำสั่งซื้อจะไม่เปลี่ยนแปลง",
        previous: "ก่อนหน้า",
        next: "ถัดไป",
        liveLink: "เปิดร้าน",
        version: "เวอร์ชัน",
        sections: {
          HERO: "โปสเตอร์หลัก",
          KINDS: "ประเภทของขวัญ",
          ARTISTS: "ศิลปิน",
          GIFTS: "ของขวัญ",
          POLICIES: "ลิงก์นโยบาย",
          HOW_IT_WORKS: "ขั้นตอนการส่ง",
          STUDIO_PROMISE: "คำมั่นจากสตูดิโอ",
          FINAL_CTA: "คำเชิญท้ายหน้า",
        },
      };
    case "vi":
      return {
        reset: "Dùng bố cục mặc định",
        title: "Trang trí cửa hàng",
        intro: "Sắp xếp trang chủ, xem trước rồi xuất bản khi đã sẵn sàng.",
        sectionTitle: "Các phần của trang",
        shown: "Hiển thị",
        required: "Luôn hiển thị",
        moveUp: "Lên trên",
        moveDown: "Xuống dưới",
        preview: "Xem trước",
        previewHint:
          "Xem nội dung đã xuất bản với bố cục đang chỉnh sửa. Không thể chuyển trang hoặc mua hàng tại đây.",
        previewUnavailable: "Hãy cấu hình địa chỉ cửa hàng để xem trước.",
        previewFailed: "Không thể tải bản xem trước. Vui lòng thử lại.",
        mobile: "Điện thoại",
        desktop: "Máy tính",
        save: "Lưu bản nháp",
        publish: "Xuất bản",
        history: "Lịch sử xuất bản",
        restore: "Khôi phục",
        noHistory: "Bố cục đã xuất bản sẽ hiển thị ở đây.",
        loading: "Đang tải…",
        saved: "Đã lưu bản nháp",
        published: "Đã xuất bản bố cục",
        restored: "Đã khôi phục bố cục",
        unsaved: "Thay đổi chưa lưu",
        draft: "Bản nháp đã lưu",
        live: "Bố cục đã xuất bản",
        error:
          "Chưa thể xác nhận kết quả. Thay đổi vẫn được giữ lại. Vui lòng thử lại.",
        conflict:
          "Người quản lý khác đã thay đổi bố cục. Hãy tải phiên bản mới nhất trước khi tiếp tục.",
        forbidden: "Tài khoản này không có quyền thực hiện thao tác.",
        reload: "Tải lại",
        discard: "Rời trang và bỏ các thay đổi bố cục chưa lưu?",
        cancel: "Hủy",
        restoreConfirm:
          "Khôi phục bố cục này? Bố cục hiện tại và bản nháp sẽ được thay thế. Hình ảnh, quà tặng và đơn hàng giữ nguyên.",
        previous: "Trước",
        next: "Tiếp",
        liveLink: "Mở cửa hàng",
        version: "Phiên bản",
        sections: {
          HERO: "Ảnh bìa chính",
          KINDS: "Loại quà tặng",
          ARTISTS: "Nghệ sĩ",
          GIFTS: "Quà tặng",
          POLICIES: "Liên kết chính sách",
          HOW_IT_WORKS: "Cách gửi quà",
          STUDIO_PROMISE: "Cam kết của studio",
          FINAL_CTA: "Lời mời cuối trang",
        },
      };
    case "es":
      return {
        reset: "Usar diseño predeterminado",
        title: "Diseño de la tienda",
        intro:
          "Organiza la página de inicio, revísala y publícala cuando esté lista.",
        sectionTitle: "Secciones de la página",
        shown: "Mostrar",
        required: "Siempre visible",
        moveUp: "Subir",
        moveDown: "Bajar",
        preview: "Vista previa",
        previewHint:
          "Contenido publicado con tus cambios de diseño. Aquí no se puede navegar ni comprar.",
        previewUnavailable:
          "Configura la dirección de la tienda para ver la vista previa.",
        previewFailed: "No se pudo cargar la vista previa. Inténtalo de nuevo.",
        mobile: "Móvil",
        desktop: "Ordenador",
        save: "Guardar borrador",
        publish: "Publicar",
        history: "Historial de publicaciones",
        restore: "Restaurar",
        noHistory: "Los diseños publicados aparecerán aquí.",
        loading: "Cargando…",
        saved: "Borrador guardado",
        published: "Diseño publicado",
        restored: "Diseño restaurado",
        unsaved: "Cambios sin guardar",
        draft: "Borrador guardado",
        live: "Diseño publicado",
        error:
          "No se pudo confirmar el resultado. Tus cambios siguen aquí. Inténtalo de nuevo.",
        conflict:
          "Otra persona actualizó este diseño. Recarga la versión más reciente para continuar.",
        forbidden: "Tu cuenta no tiene permiso para esta acción.",
        reload: "Recargar",
        discard: "¿Salir y descartar los cambios de diseño sin guardar?",
        cancel: "Cancelar",
        restoreConfirm:
          "¿Restaurar este diseño? Sustituirá el diseño y el borrador actuales. Las imágenes, los regalos y los pedidos no cambiarán.",
        previous: "Anterior",
        next: "Siguiente",
        liveLink: "Abrir tienda",
        version: "Versión",
        sections: {
          HERO: "Imagen principal",
          KINDS: "Categorías de regalos",
          ARTISTS: "Artistas",
          GIFTS: "Regalos",
          POLICIES: "Enlaces a políticas",
          HOW_IT_WORKS: "Cómo funciona",
          STUDIO_PROMISE: "Compromiso del estudio",
          FINAL_CTA: "Invitación final",
        },
      };
    case "pt":
      return {
        reset: "Usar layout padrão",
        title: "Design da loja",
        intro:
          "Organize a página inicial, confira a prévia e publique quando estiver pronta.",
        sectionTitle: "Seções da página",
        shown: "Mostrar",
        required: "Sempre visível",
        moveUp: "Mover para cima",
        moveDown: "Mover para baixo",
        preview: "Prévia",
        previewHint:
          "Conteúdo publicado com suas alterações de layout. A navegação e as compras estão desativadas aqui.",
        previewUnavailable: "Configure o endereço da loja para abrir a prévia.",
        previewFailed: "Não foi possível carregar a prévia. Tente novamente.",
        mobile: "Celular",
        desktop: "Computador",
        save: "Salvar rascunho",
        publish: "Publicar",
        history: "Histórico de publicações",
        restore: "Restaurar",
        noHistory: "Os layouts publicados aparecerão aqui.",
        loading: "Carregando…",
        saved: "Rascunho salvo",
        published: "Layout publicado",
        restored: "Layout restaurado",
        unsaved: "Alterações não salvas",
        draft: "Rascunho salvo",
        live: "Layout publicado",
        error:
          "Não foi possível confirmar o resultado. Suas alterações foram mantidas. Tente novamente.",
        conflict:
          "Outra pessoa atualizou este layout. Recarregue a versão mais recente para continuar.",
        forbidden: "Sua conta não tem permissão para esta ação.",
        reload: "Recarregar",
        discard: "Sair e descartar as alterações de layout não salvas?",
        cancel: "Cancelar",
        restoreConfirm:
          "Restaurar este layout? O layout e o rascunho atuais serão substituídos. Imagens, presentes e pedidos permanecerão iguais.",
        previous: "Anterior",
        next: "Próxima",
        liveLink: "Abrir loja",
        version: "Versão",
        sections: {
          HERO: "Imagem principal",
          KINDS: "Categorias de presentes",
          ARTISTS: "Artistas",
          GIFTS: "Presentes",
          POLICIES: "Links de políticas",
          HOW_IT_WORKS: "Como funciona",
          STUDIO_PROMISE: "Compromisso do estúdio",
          FINAL_CTA: "Convite final",
        },
      };
  }
}
