SET search_path = public;

ALTER TABLE orders DROP CONSTRAINT orders_current_payment_attempt_owner_fk;
DROP TRIGGER order_events_provider_cancel_evidence_trigger ON order_events;
ALTER TABLE order_events
  DROP CONSTRAINT order_events_provider_event_fk,
  DROP CONSTRAINT order_events_to_payment_attempt_owner_fk,
  DROP CONSTRAINT order_events_from_payment_attempt_owner_fk;
DROP TRIGGER notification_deliveries_outbox_trigger ON notification_deliveries;
DROP TRIGGER fulfillment_events_outbox_trigger ON fulfillment_events;
DROP TRIGGER cart_items_added_outbox_trigger ON cart_items;
DROP TRIGGER config_versions_payment_publication_trigger ON config_versions;
DROP TRIGGER config_versions_payment_mutation_trigger ON config_versions;
DROP TRIGGER inventory_reservations_nonterminal_payment_lock_trigger ON inventory_reservations;
DROP TRIGGER orders_nonterminal_payment_lock_trigger ON orders;
DROP TRIGGER carts_nonterminal_payment_lock_trigger ON carts;

DROP TABLE outbox_effect_receipts;
DROP TABLE outbox_dispatch_attempts;
DROP TABLE outbox_events;
DROP TABLE webhook_effects;
DROP TABLE webhook_processing_attempts;
DROP TABLE dispute_events;
DROP TABLE refund_events;
DROP TABLE payment_attempt_events;
DROP TABLE disputes;
DROP TABLE refund_items;
DROP TABLE refunds;
DROP TABLE payment_transactions;
DROP TABLE provider_event_associations;
DROP TABLE payment_attempts;
DROP TABLE provider_events;
DROP TABLE webhook_inbox;
DROP TABLE webhook_payloads;
DROP TABLE payment_config_publications;
DROP TABLE payment_route_rule_device_capabilities;
DROP TABLE payment_route_rule_currencies;
DROP TABLE payment_route_rule_markets;
DROP TABLE payment_route_rule_countries;
DROP TABLE payment_route_rules;
DROP TABLE payment_provider_config_translation_reviews;
DROP TABLE payment_provider_config_translations;
DROP TABLE payment_provider_configs;
ALTER TABLE config_versions DROP CONSTRAINT config_versions_payment_identity_unique;
DROP TABLE payment_webhook_endpoints;
DROP TABLE payment_provider_health_events;
DROP TABLE payment_provider_accounts;
DROP TABLE merchant_entities;

DROP FUNCTION assert_payment_config_publication_outbox();
DROP FUNCTION assert_dispute_state_event_outbox();
DROP FUNCTION assert_refund_state_event_outbox();
DROP FUNCTION assert_payment_state_event_outbox();
DROP FUNCTION assert_notification_request_outbox();
DROP FUNCTION assert_fulfillment_event_outbox();
DROP FUNCTION assert_cart_item_added_outbox();
DROP FUNCTION assert_outbox_event_authority();
DROP FUNCTION assert_financial_event_head();
DROP FUNCTION validate_outbox_event_shape();
DROP FUNCTION assert_dispute_evidence_and_event();
DROP FUNCTION validate_dispute_mutation();
DROP FUNCTION assert_refund_evidence_and_event();
DROP FUNCTION assert_refund_item_capacity();
DROP FUNCTION assert_refund_allocation();
DROP FUNCTION validate_refund_mutation_and_capacity();
DROP FUNCTION guard_nonterminal_payment_lock();
DROP FUNCTION assert_payment_success_aggregate_plan();
DROP FUNCTION assert_payment_attempt_evidence_and_event();
DROP FUNCTION validate_payment_attempt_mutation();
DROP FUNCTION assert_provider_event_association();
DROP FUNCTION assert_provider_transaction_ledger();
DROP FUNCTION validate_payment_transaction_evidence();
DROP FUNCTION validate_order_provider_cancel_evidence();
DROP FUNCTION validate_provider_event_association();
DROP FUNCTION validate_provider_event_evidence();
DROP FUNCTION validate_webhook_inbox_endpoint_window();
DROP FUNCTION guard_payment_webhook_endpoint_transition();
DROP FUNCTION guard_webhook_payload_transition();
DROP FUNCTION validate_payment_config_publication_event();
DROP FUNCTION assert_payment_provider_health_head();
DROP FUNCTION validate_payment_provider_health_event();
DROP FUNCTION guard_payment_provider_account_health();
DROP FUNCTION guard_payment_route_child_mutation();
DROP FUNCTION validate_payment_config_publication();
DROP FUNCTION assert_payment_provider_translation_package(uuid);
DROP FUNCTION guard_payment_config_version_mutation();
