SET search_path=public;
LOCK TABLE information_page_heads,information_page_revisions,information_page_revision_translations,information_page_translation_reviews,information_page_translation_copy_evidence,information_page_publications,information_page_receipts IN ACCESS EXCLUSIVE MODE;
DO $$ BEGIN IF EXISTS(SELECT 1 FROM information_page_revisions) OR EXISTS(SELECT 1 FROM information_page_receipts) OR EXISTS(SELECT 1 FROM information_page_publications) OR EXISTS(SELECT 1 FROM outbox_events WHERE event_type='INFORMATION_PAGE_PUBLICATION_CHANGED') OR EXISTS(SELECT 1 FROM audit_logs WHERE action LIKE 'INFORMATION_PAGE_%') THEN RAISE EXCEPTION 'information page history cannot be downgraded' USING ERRCODE='55000';END IF;END $$;
DROP TRIGGER information_page_effect_guard ON outbox_effect_receipts;
DROP TRIGGER information_page_attempt_guard ON outbox_dispatch_attempts;
DROP FUNCTION guard_information_page_dispatch_effect();
DROP TRIGGER information_page_outbox_proof ON outbox_events;
DROP INDEX information_page_outbox_once;
DROP TRIGGER outbox_events_validate_trigger ON outbox_events;
CREATE TRIGGER outbox_events_validate_trigger BEFORE INSERT ON outbox_events FOR EACH ROW EXECUTE FUNCTION validate_outbox_event_shape();
DROP TRIGGER outbox_events_authority_trigger ON outbox_events;
CREATE CONSTRAINT TRIGGER outbox_events_authority_trigger AFTER INSERT ON outbox_events DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION assert_outbox_event_authority();
DROP INDEX outbox_events_state_transition_unique_idx;
CREATE UNIQUE INDEX outbox_events_state_transition_unique_idx ON outbox_events(event_type,aggregate_type,aggregate_id,aggregate_version) WHERE event_type NOT IN('CONTENT_PUBLICATION_CHANGED','PAYMENT_CONFIG_PUBLISHED','PRICE_BOOK_PUBLISHED');
ALTER TABLE outbox_events DROP CONSTRAINT outbox_events_event_type_check;
ALTER TABLE outbox_events ADD CONSTRAINT outbox_events_event_type_check CHECK(event_type IN('CART_ITEM_ADDED','CONTENT_PUBLICATION_CHANGED','PAYMENT_STATUS_CHANGED','ORDER_PAYMENT_CONFIRMED','REFUND_STATUS_CHANGED','DISPUTE_STATUS_CHANGED','FULFILLMENT_STATUS_CHANGED','NOTIFICATION_REQUESTED','PAYMENT_CONFIG_PUBLISHED','PRICE_BOOK_PUBLISHED'));
ALTER TABLE outbox_events DROP CONSTRAINT outbox_events_aggregate_type_check;
ALTER TABLE outbox_events ADD CONSTRAINT outbox_events_aggregate_type_check CHECK(aggregate_type IN('CART','CONTENT_PUBLICATION','ORDER','PAYMENT_ATTEMPT','REFUND','DISPUTE','FULFILLMENT','NOTIFICATION_DELIVERY','PAYMENT_CONFIG','PRICE_BOOK'));
DROP FUNCTION information_page_effective_review(uuid);
DROP TABLE information_page_receipts,information_page_translation_copy_evidence,information_page_translation_reviews,information_page_revision_translations,information_page_heads,information_page_publications,information_page_revisions;
DROP FUNCTION guard_information_page_receipt(),assert_information_page_head_receipt(),assert_information_page_publication_complete(),assert_information_page_outbox(),assert_information_page_revision(),guard_information_page_head(),guard_information_page_publication(),information_page_publishable(uuid),guard_information_page_review(),guard_information_page_copy(),guard_information_page_translation(),information_page_matches(jsonb,jsonb),valid_information_page_fields(jsonb,text),valid_information_page_structure(jsonb,text),information_page_text(jsonb,integer,boolean),information_page_hash(jsonb);
