import type { PaymentCopy } from "./copy-en";
export const paymentPortuguese = {
  before: "Antes",
  after: "Depois",
  notRecorded: "Sem registro",

  title: "Configurações de pagamento",
  intro:
    "Gerencie os canais conectados. As alterações aplicam-se a novos pagamentos após a publicação.",
  loading: "Carregando configurações…",
  refresh: "Atualizar",
  retry: "Tentar novamente",
  noAccess: "Você não tem acesso às configurações de pagamento.",
  emptyAccounts:
    "Não há contas implantadas disponíveis. Peça ao administrador para conectar uma.",
  legacy:
    "A configuração atual é anterior a este editor. Crie um rascunho para gerenciá-la.",
  current: "Publicação atual",
  version: "Versão",
  edit: "Editar uma cópia",
  newDraft: "Criar rascunho",
  save: "Salvar rascunho",
  saved: "Rascunho salvo. Revise os textos para clientes antes de publicar.",
  draftHint:
    "Salvar cria uma nova versão. Textos inalterados de uma versão publicada podem manter a aprovação; textos novos ou alterados precisam de revisão independente.",
  back: "Voltar",
  channels: "Canais de pagamento",
  addChannel: "Adicionar canal",
  account: "Conta conectada",
  enabled: "Ativo para novos pagamentos",
  order: "Ordem de exibição",
  rollout: "Percentual de tráfego (%)",
  health: "Avançado: integridade do canal",
  healthHint:
    "Use a política implantada ou preencha todos os campos. Falhas técnicas podem pausar novos pagamentos.",
  failures: "Falhas antes de pausar",
  window: "Janela de falhas (segundos)",
  openDuration: "Duração da pausa (segundos)",
  probeLease: "Tempo limite da verificação (segundos)",
  probeRetry: "Intervalo de verificação (segundos)",
  text: "Textos para clientes",
  language: "Idioma",
  name: "Nome do canal",
  hint: "Orientações de pagamento",
  source: "Original em inglês",
  missing: "Em falta",
  draft: "Rascunho",
  inReview: "Aguardando revisão",
  approved: "Aprovado",
  stale: "Original alterado",
  submit: "Enviar para revisão",
  approve: "Aprovar este idioma",
  reviewHint:
    "Outra pessoa autorizada deve revisar cada idioma, incluindo o inglês.",
  routes: "Regras de disponibilidade",
  addRule: "Adicionar regra",
  remove: "Remover",
  rule: "Regra",
  method: "Método de pagamento",
  countries: "Códigos de países",
  markets: "Mercados",
  currencies: "Códigos de moedas",
  codesHint:
    "Separe os valores com vírgulas. Países e moedas devem ser compatíveis com a conta; o idioma não define o mercado.",
  minimum: "Valor mínimo (unidade menor)",
  maximum: "Valor máximo (unidade menor)",
  amountHint:
    "Os limites aplicam-se a cada moeda indicada. Os valores formatados aparecem abaixo.",
  devices: "Apresentação de pagamento exigida",
  priority: "Prioridade (menor primeiro)",
  invalid:
    "Confira os campos. Use unidades monetárias mínimas inteiras e percentuais de 0 a 100.",
  checkPublish: "Verificar alterações para publicar",
  checkRollback: "Verificar restauração",
  changes: "Alterações em relação à publicação atual",
  noChanges: "Nenhuma diferença encontrada.",
  added: "Adicionado",
  removed: "Removido",
  changed: "Alterado",
  validationFailed:
    "A publicação está bloqueada. Resolva os problemas e verifique novamente.",
  ready: "Validação concluída. Confirme as alterações para publicar.",
  reason: "Motivo",
  reasonUpdate: "Atualização operacional",
  reasonRecovery: "Restaurar configuração conhecida",
  confirm: "Revisei as alterações e confirmo esta ação.",
  publish: "Publicar configuração",
  rollback: "Restaurar esta versão",
  published:
    "Configuração publicada. Será usada em novos pagamentos conforme os nós forem atualizados.",
  publishHint:
    "Pagamentos e reembolsos existentes mantêm a conta original. Publicações e restaurações são auditadas.",
  history: "Histórico de versões",
  view: "Abrir versão",
  wasPublished: "Publicado anteriormente",
  noHistory: "Ainda não há versões gerenciadas.",
  readOnly: "Acesso somente de leitura",
  error:
    "Não foi possível confirmar a operação. Recupere a solicitação ou atualize as configurações.",
  conflict: "A versão atual mudou. Atualize antes de preparar outra alteração.",
  selfReview:
    "O autor não pode aprovar o próprio texto. Peça a outro revisor autorizado.",
  pending:
    "O resultado é incerto. Recupere a mesma solicitação antes de outra alteração.",
  recover: "Recuperar esta solicitação",
  storageUnavailable:
    "O armazenamento de recuperação não está disponível. As alterações estão desativadas.",
  reviewed: "Revisão registrada.",
  emptyRoutes: "Adicione pelo menos uma regra utilizável.",
  accountUnavailable:
    "Esta conta não está disponível para a configuração selecionada.",
  adapterUnavailable:
    "O adaptador necessário não está implantado ou está indisponível.",
  unsupportedMethod: "A conta não oferece este método de pagamento.",
  invalidRoute: "Revise o escopo, os limites e a conta desta regra.",
  translationMissing: "Preencha o nome e as orientações neste idioma.",
  translationUnapproved: "Este idioma precisa de aprovação independente.",
  translationStale: "O original em inglês mudou. Atualize e revise a tradução.",
  healthInvalid: "Preencha os ajustes de integridade dentro dos limites.",
  notPublished: "Só é possível restaurar uma versão gerenciada já publicada.",
  redirect: "Redirecionar ao provedor",
  iframe: "Quadro hospedado pelo provedor",
  component: "Componente do provedor",
  qr: "Código QR",
  channelStatus: "Estado da conexão",
  available: "Disponível",
  unavailable: "Indisponível",
  none: "Nenhum",
  unsaved: "Alterações não salvas",
} satisfies PaymentCopy;
