import type { PaymentCopy } from "./copy-en";
export const paymentVietnamese = {
  before: "Trước",
  after: "Sau",
  notRecorded: "Chưa ghi nhận",

  title: "Cài đặt thanh toán",
  intro:
    "Quản lý kênh đã kết nối. Thay đổi áp dụng cho thanh toán mới sau khi công bố.",
  loading: "Đang tải cài đặt…",
  refresh: "Tải lại",
  retry: "Thử lại",
  noAccess: "Bạn không có quyền truy cập cài đặt thanh toán.",
  emptyAccounts:
    "Chưa có tài khoản được triển khai. Hãy nhờ quản trị viên kết nối trước.",
  legacy:
    "Cấu hình hiện tại có trước trình chỉnh sửa này. Tạo bản nháp để quản lý thay đổi.",
  current: "Bản đang công bố",
  version: "Phiên bản",
  edit: "Sửa bản sao",
  newDraft: "Tạo bản nháp",
  save: "Lưu bản nháp",
  saved: "Đã lưu. Hãy duyệt nội dung hiển thị cho khách trước khi công bố.",
  draftHint:
    "Lưu sẽ tạo phiên bản mới. Nội dung không đổi từ phiên bản đã công bố có thể giữ phê duyệt; nội dung mới hoặc sửa đổi cần người khác duyệt.",
  back: "Quay lại",
  channels: "Kênh thanh toán",
  addChannel: "Thêm kênh",
  account: "Tài khoản đã kết nối",
  enabled: "Cho phép thanh toán mới",
  order: "Thứ tự hiển thị",
  rollout: "Tỷ lệ phân phối (%)",
  health: "Nâng cao: tình trạng kênh",
  healthHint:
    "Dùng chính sách đã triển khai hoặc điền rõ mọi trường. Lỗi kỹ thuật có thể tạm dừng thanh toán mới.",
  failures: "Số lần lỗi trước khi tạm dừng",
  window: "Khoảng đếm lỗi (giây)",
  openDuration: "Thời gian tạm dừng (giây)",
  probeLease: "Thời hạn kiểm tra phục hồi (giây)",
  probeRetry: "Khoảng kiểm tra phục hồi (giây)",
  text: "Nội dung hiển thị cho khách",
  language: "Ngôn ngữ",
  name: "Tên kênh",
  hint: "Hướng dẫn thanh toán",
  source: "Bản gốc tiếng Anh",
  missing: "Chưa có",
  draft: "Bản nháp",
  inReview: "Chờ duyệt",
  approved: "Đã duyệt",
  stale: "Bản gốc đã thay đổi",
  submit: "Gửi duyệt",
  approve: "Duyệt ngôn ngữ này",
  reviewHint:
    "Mỗi ngôn ngữ, kể cả tiếng Anh, phải do người có quyền khác duyệt.",
  routes: "Quy tắc phạm vi sử dụng",
  addRule: "Thêm quy tắc",
  remove: "Xóa",
  rule: "Quy tắc",
  method: "Phương thức thanh toán",
  countries: "Mã quốc gia",
  markets: "Thị trường",
  currencies: "Mã tiền tệ",
  codesHint:
    "Phân cách bằng dấu phẩy. Quốc gia và tiền tệ phải phù hợp tài khoản; ngôn ngữ không quyết định thị trường.",
  minimum: "Số tiền tối thiểu (đơn vị nhỏ nhất)",
  maximum: "Số tiền tối đa (đơn vị nhỏ nhất)",
  amountHint:
    "Giới hạn áp dụng cho từng tiền tệ đã liệt kê. Số tiền định dạng bên dưới thể hiện giá trị.",
  devices: "Khả năng giao diện thanh toán cần có",
  priority: "Ưu tiên (số nhỏ trước)",
  invalid:
    "Kiểm tra các trường. Dùng số nguyên cho đơn vị tiền nhỏ nhất và tỷ lệ từ 0 đến 100.",
  checkPublish: "Kiểm tra thay đổi để công bố",
  checkRollback: "Kiểm tra khôi phục",
  changes: "Thay đổi so với bản đang công bố",
  noChanges: "Không có khác biệt.",
  added: "Đã thêm",
  removed: "Đã xóa",
  changed: "Đã sửa",
  validationFailed:
    "Chưa thể công bố. Hãy sửa các vấn đề bên dưới rồi kiểm tra lại.",
  ready: "Đã kiểm tra. Xác nhận thay đổi để công bố.",
  reason: "Lý do",
  reasonUpdate: "Điều chỉnh vận hành",
  reasonRecovery: "Khôi phục cấu hình đã xác minh",
  confirm: "Tôi đã kiểm tra thay đổi và xác nhận thao tác này.",
  publish: "Công bố cấu hình",
  rollback: "Khôi phục phiên bản này",
  published:
    "Đã công bố. Thanh toán mới sẽ dùng cấu hình khi các nút cập nhật.",
  publishHint:
    "Thanh toán và hoàn tiền cũ giữ nguyên tài khoản. Công bố và khôi phục được ghi nhật ký.",
  history: "Lịch sử phiên bản",
  view: "Mở phiên bản",
  wasPublished: "Đã từng công bố",
  noHistory: "Chưa có phiên bản được quản lý.",
  readOnly: "Quyền chỉ đọc",
  error:
    "Chưa xác nhận được kết quả. Hãy khôi phục yêu cầu hoặc tải lại cài đặt.",
  conflict:
    "Phiên bản hiện tại đã đổi. Hãy tải lại trước khi tạo thay đổi mới.",
  selfReview: "Tác giả không thể tự duyệt. Hãy nhờ người duyệt có quyền khác.",
  pending:
    "Kết quả chưa chắc chắn. Khôi phục yêu cầu cũ trước khi thay đổi tiếp.",
  recover: "Khôi phục yêu cầu này",
  storageUnavailable:
    "Bộ nhớ khôi phục không khả dụng. Tạm khóa thay đổi đến khi khả dụng.",
  reviewed: "Đã ghi nhận thao tác duyệt.",
  emptyRoutes: "Thêm ít nhất một quy tắc dùng được.",
  accountUnavailable: "Tài khoản này không khả dụng cho cấu hình đã chọn.",
  adapterUnavailable:
    "Bộ kết nối cần thiết chưa được triển khai hoặc không khả dụng.",
  unsupportedMethod: "Tài khoản không hỗ trợ phương thức này.",
  invalidRoute: "Kiểm tra phạm vi, giới hạn và tài khoản của quy tắc.",
  translationMissing: "Điền tên kênh và hướng dẫn cho ngôn ngữ này.",
  translationUnapproved: "Ngôn ngữ này cần được người khác duyệt.",
  translationStale:
    "Bản gốc tiếng Anh đã đổi. Hãy cập nhật và duyệt lại bản dịch.",
  healthInvalid: "Điền đầy đủ cài đặt tình trạng trong giới hạn.",
  notPublished:
    "Chỉ có thể khôi phục phiên bản đã từng công bố trong hệ thống.",
  redirect: "Chuyển đến nhà cung cấp",
  iframe: "Khung thanh toán của nhà cung cấp",
  component: "Thành phần nhà cung cấp",
  qr: "Mã QR",
  channelStatus: "Trạng thái kết nối",
  available: "Khả dụng",
  unavailable: "Không khả dụng",
  none: "Không có",
  unsaved: "Thay đổi chưa lưu",
} satisfies PaymentCopy;
