export const paymentEnglish = {
  before: "Before",
  after: "After",
  notRecorded: "Not recorded",

  title: "Payment settings",
  intro:
    "Manage existing payment channels. Changes apply to new payments after publication.",
  loading: "Loading settings…",
  refresh: "Refresh",
  retry: "Try again",
  noAccess: "You do not have access to payment settings.",
  emptyAccounts:
    "No deployed accounts are available. Ask the administrator to connect an account first.",
  legacy:
    "The current configuration predates this editor. Create a draft to manage future changes.",
  current: "Current publication",
  version: "Version",
  edit: "Edit a copy",
  newDraft: "Create draft",
  save: "Save draft",
  saved: "Draft saved. Review the customer-facing text before publication.",
  draftHint:
    "Saving creates a new version. Unchanged text from a published version may keep its approval; new or changed text needs independent review.",
  back: "Back",
  channels: "Payment channels",
  addChannel: "Add channel",
  account: "Connected account",
  enabled: "Enabled for new payments",
  order: "Display order",
  rollout: "Traffic share (%)",
  health: "Advanced: channel health",
  healthHint:
    "Use the deployed policy or enter all fields explicitly. Technical failures can pause new payments.",
  failures: "Failures before pause",
  window: "Failure window (seconds)",
  openDuration: "Pause duration (seconds)",
  probeLease: "Recovery check timeout (seconds)",
  probeRetry: "Recovery check interval (seconds)",
  text: "Customer-facing text",
  language: "Language",
  name: "Channel name",
  hint: "Payment guidance",
  source: "English source",
  missing: "Missing",
  draft: "Draft",
  inReview: "Awaiting review",
  approved: "Approved",
  stale: "Source changed",
  submit: "Submit for review",
  approve: "Approve this language",
  reviewHint:
    "Another authorized person must review each language, including English.",
  routes: "Availability rules",
  addRule: "Add rule",
  remove: "Remove",
  rule: "Rule",
  method: "Payment method",
  countries: "Country codes",
  markets: "Markets",
  currencies: "Currency codes",
  codesHint:
    "Separate values with commas. Country and currency codes must match the connected account; language does not select a market.",
  minimum: "Minimum amount (minor units)",
  maximum: "Maximum amount (minor units)",
  amountHint:
    "Amount limits apply in each listed currency. The formatted amounts below show their value.",
  devices: "Required payment presentation",
  priority: "Priority (lower first)",
  invalid:
    "Check the fields. Use whole minor units and percentages from 0 to 100.",
  checkPublish: "Check changes for publication",
  checkRollback: "Check restoration",
  changes: "Changes to the current publication",
  noChanges: "No differences found.",
  added: "Added",
  removed: "Removed",
  changed: "Changed",
  validationFailed:
    "Publication is blocked. Resolve the issues below and check again.",
  ready: "Validation passed. Confirm the changes to publish.",
  reason: "Reason",
  reasonUpdate: "Operational update",
  reasonRecovery: "Restore a known configuration",
  confirm: "I checked the changes and confirm this action.",
  publish: "Publish configuration",
  rollback: "Restore this version",
  published:
    "Configuration published. New payments will use it as nodes update.",
  publishHint:
    "Existing payments and refunds keep their original account. Publication and restoration are audited.",
  history: "Version history",
  view: "Open version",
  wasPublished: "Previously published",
  noHistory: "No managed versions yet.",
  readOnly: "Read-only access",
  error:
    "The operation could not be confirmed. Try recovering the request or refresh the settings.",
  conflict:
    "The current version changed. Refresh before preparing a new change.",
  selfReview:
    "The author cannot approve their own text. Ask another authorized reviewer.",
  pending:
    "The result is uncertain. Recover the same request before making another change.",
  recover: "Recover this request",
  storageUnavailable:
    "Recovery storage is unavailable. Changes are disabled until it is available.",
  reviewed: "Review recorded.",
  emptyRoutes: "Add at least one usable route.",
  accountUnavailable:
    "This account is not available for the selected configuration.",
  adapterUnavailable: "The required adapter is not deployed or is unavailable.",
  unsupportedMethod: "The account does not support this payment method.",
  invalidRoute: "Check the scope, amount limits and account of this rule.",
  translationMissing:
    "Complete the channel name and guidance for this language.",
  translationUnapproved: "This language still needs independent approval.",
  translationStale:
    "The English source changed. Update and review this translation.",
  healthInvalid: "Complete all health settings within their allowed limits.",
  notPublished: "Only a previously published managed version can be restored.",
  redirect: "Redirect to provider",
  iframe: "Provider-hosted frame",
  component: "Provider component",
  qr: "QR code",
  channelStatus: "Connection status",
  available: "Available",
  unavailable: "Unavailable",
  none: "None",
  unsaved: "Unsaved changes",
};
export type PaymentCopy = { [K in keyof typeof paymentEnglish]: string };
