import type { PaymentCopy } from "./copy-en";
export const paymentJapanese = {
  before: "変更前",
  after: "変更後",
  notRecorded: "記録なし",

  title: "決済設定",
  intro: "接続済みの決済方法を管理します。公開後の新しい決済に適用されます。",
  loading: "設定を読み込み中…",
  refresh: "更新",
  retry: "再試行",
  noAccess: "決済設定へのアクセス権限がありません。",
  emptyAccounts:
    "利用可能な接続済みアカウントがありません。管理者に接続を依頼してください。",
  legacy: "現在の設定は旧形式です。下書きを作成して今後の変更を管理できます。",
  current: "現在の公開版",
  version: "バージョン",
  edit: "コピーを編集",
  newDraft: "下書きを作成",
  save: "下書きを保存",
  saved: "下書きを保存しました。公開前にお客様向けの文言を確認してください。",
  draftHint:
    "保存すると新しいバージョンが作成されます。公開済みの文面が変わらなければ承認を引き継げます。新規・変更した文面は別の担当者の確認が必要です。",
  back: "戻る",
  channels: "決済チャネル",
  addChannel: "チャネルを追加",
  account: "接続済みアカウント",
  enabled: "新しい決済を有効にする",
  order: "表示順",
  rollout: "利用割合（%）",
  health: "詳細：チャネルの稼働管理",
  healthHint:
    "導入済みポリシーを使用するか、全項目を入力してください。技術的な障害時に新しい決済を停止できます。",
  failures: "停止までの失敗回数",
  window: "失敗の集計期間（秒）",
  openDuration: "停止時間（秒）",
  probeLease: "復旧確認のタイムアウト（秒）",
  probeRetry: "復旧確認の間隔（秒）",
  text: "お客様向けの文言",
  language: "言語",
  name: "チャネル名",
  hint: "決済の案内",
  source: "英語の原文",
  missing: "未入力",
  draft: "下書き",
  inReview: "レビュー待ち",
  approved: "承認済み",
  stale: "原文が変更済み",
  submit: "レビューに提出",
  approve: "この言語を承認",
  reviewHint:
    "英語を含む各言語は、別の権限を持つ担当者によるレビューが必要です。",
  routes: "利用条件",
  addRule: "条件を追加",
  remove: "削除",
  rule: "条件",
  method: "決済方法",
  countries: "国コード",
  markets: "市場",
  currencies: "通貨コード",
  codesHint:
    "複数の値はカンマで区切ります。国と通貨はアカウントの条件に従い、言語で市場は変わりません。",
  minimum: "最低金額（最小通貨単位）",
  maximum: "最高金額（最小通貨単位）",
  amountHint:
    "金額の範囲は指定した各通貨に適用されます。下に実際の表示金額を示します。",
  devices: "必要な決済画面の形式",
  priority: "優先順位（小さい順）",
  invalid:
    "入力内容を確認してください。金額の最小単位は整数、割合は 0〜100 で入力します。",
  checkPublish: "公開する変更を確認",
  checkRollback: "復元内容を確認",
  changes: "現在の公開版との差分",
  noChanges: "差分はありません。",
  added: "追加",
  removed: "削除",
  changed: "変更",
  validationFailed: "公開できません。以下の問題を解決して再確認してください。",
  ready: "検証に合格しました。変更を確認して公開してください。",
  reason: "理由",
  reasonUpdate: "運用上の変更",
  reasonRecovery: "確認済みの設定に復元",
  confirm: "変更を確認し、この操作を承認します。",
  publish: "設定を公開",
  rollback: "この版に復元",
  published: "設定を公開しました。各ノードの更新後、新しい決済に適用されます。",
  publishHint:
    "既存の決済と返金は元のアカウントを維持します。公開と復元は監査記録に残ります。",
  history: "バージョン履歴",
  view: "バージョンを開く",
  wasPublished: "公開履歴あり",
  noHistory: "管理対象の版はまだありません。",
  readOnly: "読み取り専用",
  error:
    "操作結果を確認できません。元のリクエストを復元するか設定を更新してください。",
  conflict:
    "現在の版が変更されました。更新してから新しい変更を作成してください。",
  selfReview:
    "作成者は自身の文言を承認できません。別の権限を持つ担当者に依頼してください。",
  pending:
    "結果が未確定です。別の変更を行う前に元のリクエストを復元してください。",
  recover: "このリクエストを復元",
  storageUnavailable:
    "復元用ストレージを利用できないため、変更を無効にしています。",
  reviewed: "レビューを記録しました。",
  emptyRoutes: "利用可能な条件を1つ以上追加してください。",
  accountUnavailable: "この設定ではアカウントを利用できません。",
  adapterUnavailable: "必要なアダプターが未導入か利用できません。",
  unsupportedMethod: "このアカウントは決済方法をサポートしていません。",
  invalidRoute: "条件の範囲、金額の上限・下限、アカウントを確認してください。",
  translationMissing: "この言語のチャネル名と案内を入力してください。",
  translationUnapproved: "この言語は第三者の承認が必要です。",
  translationStale:
    "英語の原文が変更されました。翻訳を更新して再レビューしてください。",
  healthInvalid: "稼働管理の全項目を許容範囲内で入力してください。",
  notPublished: "以前公開した管理対象の版のみ復元できます。",
  redirect: "決済事業者へ移動",
  iframe: "事業者ホストのフレーム",
  component: "事業者のコンポーネント",
  qr: "QRコード",
  channelStatus: "接続状態",
  available: "利用可能",
  unavailable: "利用不可",
  none: "なし",
  unsaved: "未保存の変更",
} satisfies PaymentCopy;
