export const copy = {
  expired: "Caducado",
  disputeHold:
    "Este pago está en disputa o se ha revertido. Consúltalo con el proveedor de pago original antes de otro reembolso.",
  storageUnavailable:
    "Este navegador no puede guardar la recuperación de solicitudes. Restablece su almacenamiento y actualiza antes de realizar una operación financiera.",
  title: "Pagos y reembolsos",
  reconciliation: "Conciliación",
  orders: "Pedidos",
  search: "Buscar número de pedido",
  filter: "Mostrar",
  all: "Todos los pedidos",
  needsReview: "Pendiente de conciliación",
  refunds: "Reembolsos",
  disputes: "Disputas",
  empty: "No hay registros coincidentes.",
  loading: "Cargando registros de pago…",
  reload: "Actualizar",
  captured: "Cobrado",
  refunded: "Reembolsado",
  occupied: "Reembolsos en curso",
  available: "Disponible para reembolsar",
  refund: "Reembolsar",
  full: "Todo el saldo restante",
  partial: "Elegir importes por regalo",
  item: "Regalo",
  amount: "Importe del reembolso",
  total: "Total del reembolso",
  reason: "Motivo",
  customer: "Solicitud del fan",
  duplicate: "Pago duplicado",
  unavailableReason: "Regalo no disponible",
  verifyReason: "Confirmar resultado del proveedor",
  confirm: "He revisado los importes y confirmo esta acción.",
  submit: "Confirmar reembolso",
  cancelPayment: "Cancelar pedido sin pagar",
  reconcile: "Consultar resultado del proveedor",
  pendingHint:
    "Se está comprobando un resultado. Los reembolsos pendientes mantienen su importe reservado. Consulta la solicitud existente antes de crear otra. La preparación y entrega del regalo permanecen en pausa mientras el reembolso está pendiente.",
  recorded: "Solicitud registrada. El resultado actual aparece abajo.",
  retrySame: "Recuperar esta solicitud",
  uncertain:
    "No se pudo confirmar el resultado. Recupera la misma solicitud; no crees otra.",
  conflict: "El pedido ha cambiado. Actualiza antes de continuar.",
  forbidden: "No tienes permiso para esta acción.",
  invalid:
    "Introduce un importe positivo dentro del saldo disponible de cada regalo.",
  failed: "La acción no fue aceptada. Actualiza y revisa el pedido.",
  unavailable: "Los registros de pago no están disponibles temporalmente.",
  history: "Historial de reembolsos",
  payments: "Intentos de pago",
  noRecords: "Aún no hay registros.",
  open: "Abierta",
  won: "Ganada",
  lost: "Perdida",
  requested: "Solicitado",
  submitting: "Enviando",
  processing: "Procesando",
  succeeded: "Confirmado",
  unknown: "Pendiente de confirmación",
  failedStatus: "Fallido",
  canceled: "Cancelado",
  created: "Creado",
  requiresAction: "Pendiente de pago",
  paid: "Pagado",
  unpaid: "Sin pagar",
  partiallyRefunded: "Reembolso parcial",
  refundedStatus: "Reembolsado",
  none: "Ninguna",
  issue: "Requiere investigación",
  previous: "Anterior",
  next: "Siguiente",
  cancelHint:
    "La cancelación solo se completa al confirmar el resultado del pago. Un pedido pagado requiere un reembolso.",
  refundHint:
    "Los reembolsos se devuelven por la cuenta de pago original. Los importes pendientes ya están excluidos.",
  readOnly: "Tu cuenta puede consultar estos registros.",
  status: "Estado",
};
