export const copy = {
  expired: "Expired",
  disputeHold:
    "This payment is under dispute or has been reversed. Check it through the original payment provider before any further refund.",
  storageUnavailable:
    "Request recovery is unavailable in this browser. Restore browser storage and refresh before submitting a financial action.",
  title: "Payments & refunds",
  reconciliation: "Reconciliation",
  orders: "Orders",
  search: "Search order number",
  filter: "Show",
  all: "All orders",
  needsReview: "Needs reconciliation",
  refunds: "Refunds",
  disputes: "Disputes",
  empty: "No matching records.",
  loading: "Loading payment records…",
  reload: "Refresh",
  captured: "Captured",
  refunded: "Refunded",
  occupied: "Refunds in progress",
  available: "Available to refund",
  refund: "Refund",
  full: "All remaining funds",
  partial: "Choose gift amounts",
  item: "Gift",
  amount: "Refund amount",
  total: "Refund total",
  reason: "Reason",
  customer: "Fan requested",
  duplicate: "Duplicate payment",
  unavailableReason: "Gift unavailable",
  verifyReason: "Confirm provider result",
  confirm: "I have checked the amounts and confirm this action.",
  submit: "Confirm refund",
  cancelPayment: "Cancel unpaid order",
  reconcile: "Check provider result",
  pendingHint:
    "A result is still being checked. Pending refunds keep their amount reserved. Check the existing request before creating another. Gift preparation and delivery stay paused while the refund is pending.",
  recorded: "Request recorded. The current result appears below.",
  retrySame: "Recover this request",
  uncertain:
    "The result could not be confirmed. Recover the same request; do not create another.",
  conflict: "This order changed. Refresh before continuing.",
  forbidden: "You do not have permission for this action.",
  invalid: "Enter a positive amount within each gift’s available balance.",
  failed: "The action was not accepted. Refresh and check the order.",
  unavailable: "Payment records are temporarily unavailable.",
  history: "Refund history",
  payments: "Payment attempts",
  noRecords: "No records yet.",
  open: "Open",
  won: "Won",
  lost: "Lost",
  requested: "Requested",
  submitting: "Submitting",
  processing: "Processing",
  succeeded: "Confirmed",
  unknown: "Awaiting confirmation",
  failedStatus: "Failed",
  canceled: "Canceled",
  created: "Created",
  requiresAction: "Awaiting payment",
  paid: "Paid",
  unpaid: "Unpaid",
  partiallyRefunded: "Partially refunded",
  refundedStatus: "Refunded",
  none: "None",
  issue: "Needs investigation",
  previous: "Previous",
  next: "Next",
  cancelHint:
    "Cancellation is complete only after the payment result is confirmed. A paid order requires a refund.",
  refundHint:
    "Refunds return through the original payment account. Pending amounts are already excluded.",
  readOnly: "Your account can view these records.",
  status: "Status",
};
