export const copy = {
  expired: "期限切れ",
  disputeHold:
    "この支払いは異議申立て中、または取り消されています。追加の返金前に元の決済事業者で確認してください。",
  storageUnavailable:
    "このブラウザーでは申請の復元を利用できません。ブラウザーの保存機能を復旧し、更新してから操作してください。",
  title: "支払いと返金",
  reconciliation: "照合",
  orders: "注文",
  search: "注文番号を検索",
  filter: "表示",
  all: "すべての注文",
  needsReview: "照合が必要",
  refunds: "返金",
  disputes: "支払い異議",
  empty: "該当する記録はありません。",
  loading: "支払い記録を読み込み中…",
  reload: "更新",
  captured: "受領済み",
  refunded: "返金済み",
  occupied: "処理中の返金",
  available: "返金可能額",
  refund: "返金",
  full: "残額をすべて返金",
  partial: "ギフトごとの金額を選択",
  item: "ギフト",
  amount: "返金額",
  total: "返金合計",
  reason: "理由",
  customer: "ファンからの依頼",
  duplicate: "重複支払い",
  unavailableReason: "ギフトを提供できない",
  verifyReason: "決済事業者の結果を確認",
  confirm: "金額を確認し、この操作を承認します。",
  submit: "返金を確定",
  cancelPayment: "未払い注文を取り消す",
  reconcile: "決済事業者の結果を確認",
  pendingHint:
    "結果を確認中です。処理中の返金額は引き続き確保されます。新たに申請する前に元の申請を確認してください。 返金処理中はギフトの準備とお届けを一時停止します。",
  recorded: "申請を記録しました。最新の結果は下に表示されます。",
  retrySame: "元の申請を復元",
  uncertain:
    "結果を確認できません。同じ申請を復元し、新しい申請を作成しないでください。",
  conflict: "注文が更新されました。更新して続けてください。",
  forbidden: "この操作の権限がありません。",
  invalid: "各ギフトの返金可能額以内の正の金額を入力してください。",
  failed: "操作が受け付けられませんでした。更新して注文を確認してください。",
  unavailable: "支払い記録を一時的に読み込めません。",
  history: "返金履歴",
  payments: "支払い履歴",
  noRecords: "記録はまだありません。",
  open: "対応中",
  won: "勝訴",
  lost: "敗訴",
  requested: "申請済み",
  submitting: "送信中",
  processing: "処理中",
  succeeded: "確認済み",
  unknown: "確認待ち",
  failedStatus: "失敗",
  canceled: "取消済み",
  created: "作成済み",
  requiresAction: "支払い待ち",
  paid: "支払済み",
  unpaid: "未払い",
  partiallyRefunded: "一部返金済み",
  refundedStatus: "返金済み",
  none: "なし",
  issue: "調査が必要",
  previous: "前へ",
  next: "次へ",
  cancelHint:
    "支払い結果の確認後に取消が完了します。支払済みの注文には返金が必要です。",
  refundHint:
    "元の決済口座から返金します。処理中の金額は返金可能額から除外されています。",
  readOnly: "このアカウントでは記録を閲覧できます。",
  status: "状態",
};
