export const copy = {
  expired: "Expirado",
  disputeHold:
    "Este pagamento está em contestação ou foi revertido. Verifique com o provedor original antes de outro reembolso.",
  storageUnavailable:
    "Este navegador não pode salvar a recuperação de solicitações. Restaure o armazenamento e atualize antes de realizar uma operação financeira.",
  title: "Pagamentos e reembolsos",
  reconciliation: "Conciliação",
  orders: "Pedidos",
  search: "Buscar número do pedido",
  filter: "Mostrar",
  all: "Todos os pedidos",
  needsReview: "Conciliação pendente",
  refunds: "Reembolsos",
  disputes: "Contestações",
  empty: "Nenhum registro correspondente.",
  loading: "Carregando registros de pagamento…",
  reload: "Atualizar",
  captured: "Recebido",
  refunded: "Reembolsado",
  occupied: "Reembolsos em andamento",
  available: "Disponível para reembolso",
  refund: "Reembolsar",
  full: "Todo o saldo restante",
  partial: "Escolher valores por presente",
  item: "Presente",
  amount: "Valor do reembolso",
  total: "Total do reembolso",
  reason: "Motivo",
  customer: "Solicitação do fã",
  duplicate: "Pagamento duplicado",
  unavailableReason: "Presente indisponível",
  verifyReason: "Confirmar resultado do provedor",
  confirm: "Verifiquei os valores e confirmo esta ação.",
  submit: "Confirmar reembolso",
  cancelPayment: "Cancelar pedido não pago",
  reconcile: "Consultar resultado do provedor",
  pendingHint:
    "Um resultado ainda está sendo verificado. Reembolsos pendentes mantêm o valor reservado. Consulte a solicitação existente antes de criar outra. A preparação e a entrega do presente ficam pausadas enquanto o reembolso está pendente.",
  recorded: "Solicitação registrada. O resultado atual aparece abaixo.",
  retrySame: "Recuperar esta solicitação",
  uncertain:
    "Não foi possível confirmar o resultado. Recupere a mesma solicitação; não crie outra.",
  conflict: "O pedido mudou. Atualize antes de continuar.",
  forbidden: "Você não tem permissão para esta ação.",
  invalid:
    "Insira um valor positivo dentro do saldo disponível de cada presente.",
  failed: "A ação não foi aceita. Atualize e verifique o pedido.",
  unavailable: "Os registros de pagamento estão temporariamente indisponíveis.",
  history: "Histórico de reembolsos",
  payments: "Tentativas de pagamento",
  noRecords: "Ainda não há registros.",
  open: "Aberta",
  won: "Ganha",
  lost: "Perdida",
  requested: "Solicitado",
  submitting: "Enviando",
  processing: "Processando",
  succeeded: "Confirmado",
  unknown: "Aguardando confirmação",
  failedStatus: "Falhou",
  canceled: "Cancelado",
  created: "Criado",
  requiresAction: "Aguardando pagamento",
  paid: "Pago",
  unpaid: "Não pago",
  partiallyRefunded: "Parcialmente reembolsado",
  refundedStatus: "Reembolsado",
  none: "Nenhuma",
  issue: "Requer investigação",
  previous: "Anterior",
  next: "Próxima",
  cancelHint:
    "O cancelamento só termina após a confirmação do resultado do pagamento. Um pedido pago exige reembolso.",
  refundHint:
    "Os reembolsos retornam pela conta de pagamento original. Valores pendentes já estão excluídos.",
  readOnly: "Sua conta pode consultar estes registros.",
  status: "Status",
};
