export const copy = {
  expired: "已过期",
  disputeHold:
    "此付款正处于拒付处理或已被扣回。进一步退款前，请通过原支付渠道核对。",
  storageUnavailable:
    "此浏览器暂时无法保存操作恢复记录。请恢复浏览器存储并刷新后再提交资金操作。",
  title: "付款与退款",
  reconciliation: "对账",
  orders: "订单",
  search: "搜索订单号",
  filter: "显示",
  all: "全部订单",
  needsReview: "待对账",
  refunds: "退款",
  disputes: "拒付",
  empty: "暂无符合条件的记录。",
  loading: "正在读取付款记录…",
  reload: "刷新",
  captured: "已收款",
  refunded: "已退款",
  occupied: "退款处理中",
  available: "可退金额",
  refund: "退款",
  full: "退还全部剩余金额",
  partial: "选择礼物退款金额",
  item: "礼物",
  amount: "退款金额",
  total: "退款合计",
  reason: "原因",
  customer: "粉丝申请",
  duplicate: "重复付款",
  unavailableReason: "礼物无法提供",
  verifyReason: "核对支付方结果",
  confirm: "我已核对金额并确认本次操作。",
  submit: "确认退款",
  cancelPayment: "取消未付款订单",
  reconcile: "核对支付方结果",
  pendingHint:
    "仍有结果待核对。处理中退款的金额会继续占用额度，请先核对原请求，勿重复申请。 退款处理中将暂停礼物准备与送达。",
  recorded: "请求已登记，请查看下方最新结果。",
  retrySame: "恢复原请求",
  uncertain: "暂时无法确认结果。请恢复同一请求，勿创建新的请求。",
  conflict: "订单已更新，请刷新后继续。",
  forbidden: "你没有此操作的权限。",
  invalid: "请输入大于零且不超过每件礼物可退余额的金额。",
  failed: "操作未被接受，请刷新并核对订单。",
  unavailable: "付款记录暂时无法读取。",
  history: "退款记录",
  payments: "付款记录",
  noRecords: "暂无记录。",
  open: "处理中",
  won: "已胜诉",
  lost: "已败诉",
  requested: "已申请",
  submitting: "提交中",
  processing: "处理中",
  succeeded: "已确认",
  unknown: "等待确认",
  failedStatus: "失败",
  canceled: "已取消",
  created: "已创建",
  requiresAction: "等待付款",
  paid: "已付款",
  unpaid: "未付款",
  partiallyRefunded: "部分退款",
  refundedStatus: "已退款",
  none: "无",
  issue: "需要核查",
  previous: "上一页",
  next: "下一页",
  cancelHint: "只有确认付款结果后才会完成取消；已付款的订单需要退款。",
  refundHint: "退款经原支付账户原路退回，可退金额已扣除处理中退款。",
  readOnly: "你的账户可以查看这些记录。",
  status: "状态",
};
