export const copy = {
  expired: "Hết hạn",
  disputeHold:
    "Khoản thanh toán đang tranh chấp hoặc đã bị thu hồi. Hãy kiểm tra qua nhà cung cấp ban đầu trước khi hoàn tiền thêm.",
  storageUnavailable:
    "Trình duyệt này không thể lưu thông tin khôi phục yêu cầu. Hãy khôi phục bộ nhớ trình duyệt và làm mới trước khi thao tác tài chính.",
  title: "Thanh toán và hoàn tiền",
  reconciliation: "Đối soát",
  orders: "Đơn hàng",
  search: "Tìm mã đơn hàng",
  filter: "Hiển thị",
  all: "Tất cả đơn hàng",
  needsReview: "Cần đối soát",
  refunds: "Hoàn tiền",
  disputes: "Tranh chấp",
  empty: "Không có bản ghi phù hợp.",
  loading: "Đang tải lịch sử thanh toán…",
  reload: "Làm mới",
  captured: "Đã thu",
  refunded: "Đã hoàn",
  occupied: "Đang hoàn tiền",
  available: "Số tiền có thể hoàn",
  refund: "Hoàn tiền",
  full: "Toàn bộ số tiền còn lại",
  partial: "Chọn số tiền theo quà",
  item: "Quà tặng",
  amount: "Số tiền hoàn",
  total: "Tổng tiền hoàn",
  reason: "Lý do",
  customer: "Người hâm mộ yêu cầu",
  duplicate: "Thanh toán trùng",
  unavailableReason: "Không thể cung cấp quà",
  verifyReason: "Xác nhận kết quả nhà cung cấp",
  confirm: "Tôi đã kiểm tra số tiền và xác nhận thao tác này.",
  submit: "Xác nhận hoàn tiền",
  cancelPayment: "Hủy đơn chưa thanh toán",
  reconcile: "Kiểm tra kết quả nhà cung cấp",
  pendingHint:
    "Một kết quả vẫn đang được kiểm tra. Khoản hoàn đang chờ vẫn giữ hạn mức. Hãy kiểm tra yêu cầu hiện tại trước khi tạo yêu cầu khác. Việc chuẩn bị và giao quà sẽ tạm dừng khi khoản hoàn tiền đang chờ.",
  recorded: "Đã ghi nhận yêu cầu. Kết quả mới nhất hiển thị bên dưới.",
  retrySame: "Khôi phục yêu cầu này",
  uncertain:
    "Chưa xác nhận được kết quả. Hãy khôi phục cùng yêu cầu, không tạo yêu cầu mới.",
  conflict: "Đơn hàng đã thay đổi. Hãy làm mới trước khi tiếp tục.",
  forbidden: "Bạn không có quyền thực hiện thao tác này.",
  invalid: "Nhập số tiền dương không vượt quá số dư có thể hoàn của từng quà.",
  failed: "Thao tác không được chấp nhận. Hãy làm mới và kiểm tra đơn hàng.",
  unavailable: "Tạm thời không thể đọc lịch sử thanh toán.",
  history: "Lịch sử hoàn tiền",
  payments: "Lần thanh toán",
  noRecords: "Chưa có bản ghi.",
  open: "Đang xử lý",
  won: "Thắng tranh chấp",
  lost: "Thua tranh chấp",
  requested: "Đã yêu cầu",
  submitting: "Đang gửi",
  processing: "Đang xử lý",
  succeeded: "Đã xác nhận",
  unknown: "Chờ xác nhận",
  failedStatus: "Thất bại",
  canceled: "Đã hủy",
  created: "Đã tạo",
  requiresAction: "Chờ thanh toán",
  paid: "Đã thanh toán",
  unpaid: "Chưa thanh toán",
  partiallyRefunded: "Đã hoàn một phần",
  refundedStatus: "Đã hoàn tiền",
  none: "Không có",
  issue: "Cần kiểm tra",
  previous: "Trước",
  next: "Tiếp",
  cancelHint:
    "Chỉ hoàn tất hủy sau khi xác nhận kết quả thanh toán. Đơn đã thanh toán cần được hoàn tiền.",
  refundHint:
    "Tiền được hoàn qua tài khoản thanh toán ban đầu. Số tiền đang chờ đã được trừ khỏi hạn mức.",
  readOnly: "Tài khoản của bạn có thể xem các bản ghi này.",
  status: "Trạng thái",
};
