import type { ExceptionsCopy } from "./copy-en";
export const exceptionpt: ExceptionsCopy = {
  title: "Pendentes",
  intro: "Revise os processos interrompidos e siga o próximo passo seguro.",
  category: "Tipo",
  all: "Todos os tipos",
  webhook: "Eventos de pagamento",
  deadLetter: "Tarefas com falha",
  payment: "Pagamentos não confirmados",
  notification: "Notificações com falha",
  status: "Estado",
  open: "Precisam de atenção",
  allStates: "Todos os estados",
  filter: "Aplicar filtros",
  refresh: "Atualizar",
  back: "Voltar à lista",
  loading: "Carregando…",
  empty: "Nenhum item encontrado.",
  previous: "Anterior",
  next: "Seguinte",
  view: "Ver",
  order: "Pedido",
  attempts: "Tentativas",
  updated: "Atualização",
  nextStep: "Próximo passo",
  history: "Operações recentes",
  noHistory: "Nenhuma operação registrada.",
  reason: "Motivo",
  chooseReason: "Selecione um motivo",
  retryRepair: "Tentar após o reparo",
  verifyStatus: "Verificar estado do provedor",
  retryNotificationReason: "Repetir uma notificação com falha",
  reviewReason: "Revisão do operador",
  confirm: "Revisei este item e confirmo a operação abaixo.",
  submit: "Confirmar operação",
  replay: "Reprocessar evento verificado",
  retryDeadLetter: "Repetir tarefa original",
  reconcile: "Consultar o provedor de pagamento original",
  retryNotification: "Repetir notificação com falha",
  replayHint:
    "Processa novamente o evento verificado salvo. Pagamentos, reembolsos, entregas e notificações continuam protegidos contra duplicação.",
  deadLetterHint: "Executa a tarefa com o evento e o consumidor originais.",
  reconcileHint:
    "Consulta o estado no provedor original. Não cria uma nova cobrança.",
  notificationHint:
    "Solicita uma nova tentativa controlada. O servidor verifica o histórico de entrega e as condições.",
  readOnly: "Seu acesso é de leitura. Peça a ação a uma pessoa autorizada.",
  inProgress:
    "O processamento está em andamento. Atualize para ver o resultado.",
  complete: "Este item está concluído. Nenhuma outra ação é necessária.",
  manualReview: "Este item precisa de investigação antes de continuar.",
  unsupported: "Este tipo de tarefa precisa de revisão técnica.",
  notificationUncertain:
    "A entrega é incerta. Verifique o resultado antes de reenviar.",
  notificationExpired:
    "O prazo para repetir expirou. Revise o histórico com o suporte.",
  notificationSuperseded:
    "Existe uma notificação posterior. Revise a mais recente.",
  notRetryable:
    "O estado atual não permite outra tentativa. Atualize ou peça uma revisão.",
  inconsistent:
    "Os registros de origem não coincidem. Peça uma revisão técnica.",
  pending: "Pendente",
  processing: "Em processamento",
  failed: "Falhou",
  unknown: "Não confirmado",
  succeeded: "Concluído",
  review: "Precisa de revisão",
  expired: "Expirado",
  requested: "Solicitado",
  error: "Não foi possível carregar as informações. Atualize novamente.",
  forbidden: "Suas permissões mudaram. Atualize para verificá-las.",
  conflict: "O item mudou. Atualize e revise antes de enviar novamente.",
  uncertain:
    "O resultado não foi confirmado. Recupere a solicitação original antes de iniciar outra ação.",
  storageUnavailable:
    "O armazenamento de recuperação está indisponível. Restaure o armazenamento do navegador e recarregue.",
  recover: "Recuperar solicitação original",
  queued: "Solicitação registrada. Atualize para ver o andamento.",
};
