import type { ExceptionsCopy } from "./copy-en";
export const exceptionvi: ExceptionsCopy = {
  title: "Cần xử lý",
  intro:
    "Kiểm tra tiến trình bị gián đoạn và thực hiện bước tiếp theo an toàn.",
  category: "Loại",
  all: "Tất cả loại",
  webhook: "Sự kiện thanh toán",
  deadLetter: "Tác vụ thất bại",
  payment: "Thanh toán chưa xác nhận",
  notification: "Thông báo thất bại",
  status: "Trạng thái",
  open: "Cần chú ý",
  allStates: "Tất cả trạng thái",
  filter: "Áp dụng bộ lọc",
  refresh: "Làm mới",
  back: "Quay lại danh sách",
  loading: "Đang tải…",
  empty: "Không có mục phù hợp.",
  previous: "Trước",
  next: "Tiếp",
  view: "Xem",
  order: "Đơn hàng",
  attempts: "Số lần thử",
  updated: "Cập nhật",
  nextStep: "Bước tiếp theo",
  history: "Thao tác gần đây",
  noHistory: "Chưa có thao tác được ghi nhận.",
  reason: "Lý do",
  chooseReason: "Chọn lý do",
  retryRepair: "Thử lại sau khi sửa",
  verifyStatus: "Kiểm tra trạng thái nhà cung cấp",
  retryNotificationReason: "Thử lại thông báo thất bại",
  reviewReason: "Nhân viên kiểm tra",
  confirm: "Tôi đã kiểm tra mục này và xác nhận thao tác bên dưới.",
  submit: "Xác nhận thao tác",
  replay: "Xử lý lại sự kiện đã xác minh",
  retryDeadLetter: "Thử lại tác vụ gốc",
  reconcile: "Kiểm tra với nhà cung cấp thanh toán gốc",
  retryNotification: "Thử lại thông báo thất bại",
  replayHint:
    "Xử lý lại sự kiện đã xác minh được lưu. Hệ thống vẫn ngăn thanh toán, hoàn tiền, giao quà và thông báo trùng lặp.",
  deadLetterHint: "Chạy lại tác vụ với sự kiện và trình xử lý gốc.",
  reconcileHint:
    "Tra cứu trạng thái từ nhà cung cấp gốc. Thao tác này không tạo khoản thu mới.",
  notificationHint:
    "Yêu cầu thử lại có kiểm soát. Máy chủ kiểm tra lịch sử gửi và điều kiện thử lại.",
  readOnly: "Bạn chỉ có quyền xem. Hãy nhờ người có quyền xử lý.",
  inProgress: "Đang xử lý. Làm mới để xem kết quả.",
  complete: "Mục này đã hoàn tất. Không cần thao tác thêm.",
  manualReview: "Cần điều tra trước khi tiếp tục xử lý.",
  unsupported: "Loại tác vụ này cần bộ phận kỹ thuật kiểm tra.",
  notificationUncertain: "Kết quả gửi chưa rõ. Cần xác minh trước khi gửi lại.",
  notificationExpired:
    "Đã hết hạn thử lại. Liên hệ hỗ trợ để kiểm tra lịch sử gửi.",
  notificationSuperseded:
    "Đã có thông báo tiếp theo. Hãy xem thông báo mới nhất.",
  notRetryable:
    "Trạng thái hiện tại không cho phép thử lại. Làm mới hoặc yêu cầu kiểm tra.",
  inconsistent:
    "Dữ liệu nguồn không khớp. Hãy yêu cầu bộ phận kỹ thuật kiểm tra.",
  pending: "Đang chờ",
  processing: "Đang xử lý",
  failed: "Thất bại",
  unknown: "Chưa xác nhận",
  succeeded: "Hoàn tất",
  review: "Cần kiểm tra",
  expired: "Hết hạn",
  requested: "Đã yêu cầu",
  error: "Không tải được thông tin. Hãy làm mới.",
  forbidden: "Quyền truy cập đã thay đổi. Làm mới để kiểm tra.",
  conflict: "Mục đã thay đổi. Làm mới và kiểm tra trước khi gửi lại.",
  uncertain:
    "Kết quả thao tác chưa được xác nhận. Khôi phục yêu cầu gốc trước khi thực hiện thao tác khác.",
  storageUnavailable:
    "Không lưu được thông tin khôi phục. Hãy bật lại bộ nhớ trình duyệt và tải lại.",
  recover: "Khôi phục yêu cầu gốc",
  queued: "Đã ghi nhận yêu cầu. Làm mới để xem tiến trình.",
};
