import type { ExceptionsCopy } from "./copy-en";
export const exceptionja: ExceptionsCopy = {
  title: "要対応",
  intro: "中断した処理を確認し、安全な次の手順に進みます。",
  category: "種類",
  all: "すべての種類",
  webhook: "決済イベント",
  deadLetter: "失敗した処理",
  payment: "未確認の決済",
  notification: "通知の失敗",
  status: "状態",
  open: "対応が必要",
  allStates: "すべての状態",
  filter: "絞り込む",
  refresh: "更新",
  back: "一覧に戻る",
  loading: "読み込み中…",
  empty: "該当する項目はありません。",
  previous: "前へ",
  next: "次へ",
  view: "詳細",
  order: "注文",
  attempts: "試行回数",
  updated: "更新日時",
  nextStep: "次の手順",
  history: "最近の操作",
  noHistory: "操作履歴はありません。",
  reason: "理由",
  chooseReason: "理由を選択",
  retryRepair: "修復後に再試行",
  verifyStatus: "決済会社の状態を確認",
  retryNotificationReason: "失敗した通知を再試行",
  reviewReason: "担当者による確認",
  confirm: "この項目を確認し、以下の操作を実行します。",
  submit: "操作を確定",
  replay: "検証済みイベントを再処理",
  retryDeadLetter: "元の処理を再試行",
  reconcile: "元の決済会社に確認",
  retryNotification: "失敗した通知を再試行",
  replayHint:
    "保存済みの検証されたイベントを再処理します。決済、返金、配送、通知の重複は引き続き防止されます。",
  deadLetterHint: "元のイベントと処理先で再実行します。",
  reconcileHint: "元の決済会社に状況を照会します。新たな請求は作成しません。",
  notificationHint:
    "失敗した通知の再試行を申請します。サーバーが送信履歴と条件を再確認します。",
  readOnly: "閲覧のみ可能です。権限のある担当者に依頼してください。",
  inProgress: "処理中です。更新して結果を確認してください。",
  complete: "この項目は完了しています。追加の操作は不要です。",
  manualReview: "続行する前に調査が必要です。",
  unsupported: "この処理は技術担当者の確認が必要です。",
  notificationUncertain:
    "送信結果が不明です。再送前に送信結果を確認してください。",
  notificationExpired:
    "再試行期限が切れました。サポート担当者と送信履歴を確認してください。",
  notificationSuperseded:
    "後続の通知があります。最新の通知を確認してください。",
  notRetryable:
    "現在の状態では再試行できません。更新または確認を依頼してください。",
  inconsistent: "元の記録が一致しません。技術担当者に依頼してください。",
  pending: "待機中",
  processing: "処理中",
  failed: "失敗",
  unknown: "未確認",
  succeeded: "完了",
  review: "要確認",
  expired: "期限切れ",
  requested: "申請済み",
  error: "読み込めませんでした。再度更新してください。",
  forbidden: "権限が変更されました。更新して確認してください。",
  conflict: "状態が変更されました。更新して再確認してください。",
  uncertain:
    "操作結果が未確認です。別の操作を開始する前に元のリクエストを復元してください。",
  storageUnavailable:
    "復元情報を保存できません。ブラウザーの保存機能を復旧して再読み込みしてください。",
  recover: "元のリクエストを復元",
  queued: "申請を記録しました。更新して処理状況を確認してください。",
};
