import type { ExceptionsCopy } from "./copy-en";
export const exceptionzhCN: ExceptionsCopy = {
  title: "待处理",
  intro: "查看处理中断的事项，按提示完成下一步。",
  category: "类型",
  all: "全部类型",
  webhook: "支付事件",
  deadLetter: "重试失败",
  payment: "支付待确认",
  notification: "通知失败",
  status: "状态",
  open: "待处理事项",
  allStates: "全部状态",
  filter: "应用筛选",
  refresh: "刷新",
  back: "返回列表",
  loading: "正在加载…",
  empty: "没有符合条件的事项。",
  previous: "上一页",
  next: "下一页",
  view: "查看",
  order: "订单",
  attempts: "尝试次数",
  updated: "更新时间",
  nextStep: "下一步",
  history: "最近操作",
  noHistory: "暂无操作记录。",
  reason: "操作原因",
  chooseReason: "选择原因",
  retryRepair: "修复后重试",
  verifyStatus: "核实渠道状态",
  retryNotificationReason: "重试失败通知",
  reviewReason: "人工复核",
  confirm: "我已核对此事项，并确认执行以下操作。",
  submit: "确认操作",
  replay: "重新处理已验证事件",
  retryDeadLetter: "重试原任务",
  reconcile: "向原支付渠道核实",
  retryNotification: "重试失败通知",
  replayHint:
    "重新处理已保存且通过验证的事件。既有付款、退款、履约和通知效果仍会去重。",
  deadLetterHint: "使用原事件和原处理程序重新执行任务。",
  reconcileHint: "向原渠道查询这笔支付的状态，不会创建新的扣款。",
  notificationHint:
    "申请受控重试失败通知，服务端会重新核对投递历史与重试条件。",
  readOnly: "你目前只能查看，请由有权限的人员处理。",
  inProgress: "正在处理，请刷新查看结果。",
  complete: "此事项已完成，无需继续操作。",
  manualReview: "需先调查此事项，确认后才能继续处理。",
  unsupported: "此任务类型需要技术人员检查。",
  notificationUncertain: "投递结果不确定，需先核实投递结果，再决定是否重发。",
  notificationExpired: "重试期限已过，请联系支持人员核对投递历史。",
  notificationSuperseded: "已有后续通知，请查看最新通知。",
  notRetryable: "当前状态不允许重试，请刷新或申请复核。",
  inconsistent: "来源记录不一致，请联系技术人员检查。",
  pending: "等待处理",
  processing: "处理中",
  failed: "失败",
  unknown: "待确认",
  succeeded: "已完成",
  review: "需复核",
  expired: "已过期",
  requested: "已申请",
  error: "暂时无法读取，请刷新重试。",
  forbidden: "你的权限已变化，请刷新核对当前权限。",
  conflict: "事项状态已变化，请刷新并核对后重新操作。",
  uncertain: "操作结果尚未确认，请先恢复原请求，再发起其他操作。",
  storageUnavailable:
    "无法保存恢复信息，操作已停用。请恢复浏览器存储后重新加载。",
  recover: "恢复原请求",
  queued: "请求已记录，请刷新查看处理进度。",
};
